### ISSUE TITLE
An unknown error occurred.

### ISSUE THREAD

**Issue by csimpi** [jwilsson/spotify-web-api-php#102]
Hi, thanks for this awesome API!
I got a problem and I've tried to debug it without any luck.
I have a javascript that calls a function after any 5-10 sec randomly. That function gets data from Spotify API through my PHP file that uses your library. 
It works well for hundred times without any issue, then I got this error message very randomly. 

I use client credentials authentication, there is some problem with that part, as I can see.

Thx, Peter

The error message: 

`Fatal error: Uncaught SpotifyWebAPI\SpotifyWebAPIException: An unknown error occurred. in /var/www/mochart/public/vendor/jwilsson/spotify-web-api-php/src/Request.php:44Stack trace:#0 /var/www/mochart/public/vendor/jwilsson/spotify-web-api-php/src/Request.php(222): SpotifyWebAPI\Request->parseBody(NULL, 502)#1 /var/www/mochart/public/vendor/jwilsson/spotify-web-api-php/src/Request.php(88): SpotifyWebAPI\Request->send('POST', 'https://account...', 'grant_type=clie...', Array)#2 /var/www/mochart/public/vendor/jwilsson/spotify-web-api-php/src/Session.php(168): SpotifyWebAPI\Request->account('POST', '/api/token', Array, Array)#3 /var/www/mochart/public/api.php(84): SpotifyWebAPI\Session->requestCredentialsToken()#4 /var/www/mochart/public/api.php(34): spotiAuth('guest')#5 {main} thrown in /var/www/mochart/public/vendor/jwilsson/spotify-web-api-php/src/Request.php on line 44`

**Comment by jwilsson** [comment]
Hi!
It looks like Spotify is returning you a `502 Bad Gateway` server error. I'd file an issue over at [their repo](https://github.com/spotify/web-api) and wrap your call to `Session->requestCredentialsToken()` in a `try/catch` where you retry the request and prevents it from crashing completely.

**Comment by jwilsson** [comment]
Closing this since I'm pretty sure it's an issue on Spotify's end. Just give me a shout if you want it reopened!
