### ISSUE TITLE
Get Artist's Albums doc question

### ISSUE THREAD

**Issue by jotasprout** [jwilsson/spotify-web-api-php#103]
In **fetching-catalog-information.md**, under **Getting an artist's albums**, should the _'ALBUM_ID'_ parameter actually be _'ARTIST_ID'_?

**Comment by jwilsson** [comment]
Hi!
Yes, it should! Just a copy-paste error on my side. Would you be interested in sending a quick PR for it? Otherwise, I'll get it updated over the weekend.

Cheers!

**Comment by jotasprout** [comment]
Sorry. I didn't see your reply until just now. Wish I'd spotted that during Hacktoberfest!
