### ISSUE TITLE
CronJob Problem

### ISSUE THREAD

**Issue by tma-bhr** [jwilsson/spotify-web-api-php#106]
Hello I am trying to make an app which is getting users Current Track and set it is a status in a differenet platform.
Is there a way to save some "token" and make this code called after x minutes. Because Spotify uses oAuth user must log in and login again for using app.

I will use $api->getMyCurrentTrack() function to get current track. But also I need to make setAccesstoken which I am going to save in DB.
What can be auth method for this ?

**Comment by jwilsson** [comment]
Hi!
After authenticating the user the first time, you'll get a [refresh token](https://github.com/jwilsson/spotify-web-api-php/blob/master/docs/examples/access-token-with-authorization-code-flow.md#refreshing-an-access-token) which can later be used to refresh the access token without any user interaction.

So, save the refresh token together with the access token in your DB and refresh when necessary.
