### ISSUE TITLE
Playing a playlist

### ISSUE THREAD

**Issue by TheCanadians** [jwilsson/spotify-web-api-php#107]
Hey,
is it possible to automatically play a whole playlist with the play() method?

**Comment by jwilsson** [comment]
Hi!
Yes, pass the playlist URI as a `context_uri` to the `play()` call, like this:

```php
$api->play('', [
    'context_uri' => 'PLAYLIST_URI', // Something like spotify:user:USER_ID:playlist:PLAYLIST_ID
]);
```

**Comment by TheCanadians** [comment]
Thanks for your answer, that works.. kind of. When I try to play my playlist, I get the 202 status consecutively until the maximum excecution time is exceeded.

`
function playPlaylist() {
  try {
    $playlists = $GLOBALS['api']->getUserPlaylists($GLOBALS['api']->me()->id, [
        'limit' => 1
    ]);
    $context_uri = $playlists->items[0]->uri;
    $GLOBALS['api']->play(false, [
      'context_uri' => $context_uri,
    ]);
    $lastResponse = $GLOBALS['api']->getLastResponse();
    if ($lastResponse['status'] == 202) {
      print_r($lastResponse);
      sleep(5);
      playPlaylist();
    }
    else {
      print_r($lastResponse);
      echo "SUCCESS!";

      $current = $GLOBALS['api']->getMyCurrentTrack();
      checkTime($current->item->duration_ms);
    }
  }
  catch (Exception $e) {
    echo $e;
  }
}
`
This is how I'm trying to play playlists currently. I can't see anything obviously wrong with that.
Where is the error then?
