### ISSUE TITLE
issue after redirect with getAuthorizeUrl

### ISSUE THREAD

**Issue by benjion** [jwilsson/spotify-web-api-php#109]
Hi,

i've got a small issue when i redirect to spotify in order to login , using $session->getAuthorizeUrl($options);

i'm successfully redirected to the provided url, but i've got blank page. if i refresh the page, i suddenly get the spotify login button.

i'm using mozilla Quantum. I don't know what is wrong with this browser.

there is no issue whith Edge or Chrome.

has somebody the same issue ?

**Comment by jwilsson** [comment]
Hi!
I recommend you to file an issue over at [Spotify's API repo](https://github.com/spotify/web-api/issues).
