### ISSUE TITLE
Urlencode user id's in POST/PUT requests

### ISSUE THREAD

**Issue by PouleR** [jwilsson/spotify-web-api-php#111]
When using a POST or PUT request to Spotify with a username like '#username' the request fails:

``POST https://api.spotify.com/v1/users/#username/playlists` resulted in a `404 Not Found``

When the user id is url encoded the request succeeds. It's difficult to test since you need to have access to an account that has this kind of username (in this case that starts with a '#').

A possible solution could be to always urlencode the userId in post/put requests, since I haven't noticed this behaviour with GET requests.

**Comment by jwilsson** [comment]
Hi!
Thanks for the report.

It's pretty strange, though. I just created a test account with a "#" in the name, and I get a `404` when I try to use a POST endpoint without URL encoding it. But when I try to URL encode it, I get a `403` response with the message `You cannot create a playlist for another user`.

I'm gonna file an issue with Spotify and see what they say about it. If the solution is for us to URL encode it on our end, I'm totally fine with that.

**Comment by jwilsson** [comment]
Hi again!
This seems to be fixed on Spotify's end, so I'm gonna close this.

Just give me a shout if further work is needed!
