### ISSUE TITLE
New Refresh Token

### ISSUE THREAD

**Issue by Hickmeister** [jwilsson/spotify-web-api-php#113]
Is there a way to get a new Refresh token after using a previous Refresh token to gain a new Access token?
Because on the Spotify docs it says under the authorization code flow page 

**refresh_token | string |** :   "A token that can be sent to the Spotify Accounts service in place of an authorization code. (When the access code expires, send a POST request to the Accounts service /api/token endpoint, but use this code in place of an authorization code. A new access token will be returned.  **A new refresh token might be returned too**.)"

So would a new refresh token be sent aswell?

**Comment by jwilsson** [comment]
Hi!
It seems we missed that part in the `Session::refreshAccessToken()` method, so it won't set a new refresh token, if one exists in the response. 

Would you be interested in submitting a PR and setting a new refresh token if one is included?

**Comment by andersborgabiro** [comment]
Isn't the whole point that a refresh token is a constant? What would be the gain if it changed?

**Comment by jwilsson** [comment]
@andersborgabiro I don't know why a new refresh token would be included (unless it's been revoked for some reason) but I think the server is allowed to decide if it wants to generate a new one or not. So I definitely think we need to support that case.

**Comment by andersborgabiro** [comment]
Understood and agreed.

**Comment by jwilsson** [comment]
A fix for this has been released in `2.1.1`.
