### ISSUE TITLE
request.php broken on line 194

### ISSUE THREAD

**Issue by outspokenmagazine** [jwilsson/spotify-web-api-php#121]
original line 194
$url .= '/?' . $parameters;

was ending up every search request in a 404 response for me.
I removed the / to:
$url .= '?' . $parameters;

now all works 

I did that by following the spotify web api reference call

**Comment by jwilsson** [comment]
Hmm, strange. 

When I try, everything works. I tried with cURL as well, both with and without a slash before the question mark.

Could you post the code you're using? And which version of this library are you using?

**Comment by outspokenmagazine** [comment]
Hey, you are right. I tested with straight curl and it does not make any difference there.
Thats strange indeed.

I downloaded your package via composer and I am currently using 2.2.0 (in regards to what the changelog says)

and here is what I am doing in my code in detail:


              $artistname = 'slayer';

              require 'vendor/autoload.php';
              $session = new SpotifyWebAPI\Session(
                  'xxxxx',
                  'xxxxx'
              );

              $session->requestCredentialsToken();
              $accessToken = $session->getAccessToken();
              $api = new SpotifyWebAPI\SpotifyWebAPI();
              $api->setAccessToken($accessToken);
              $results = $api->search($artistname, 'artist');

Maybe I just did a rookies mistake and misunderstand how to use it. The last line was ending up in the 404 response from spotify, which I then was able to track down what I wrote in the initial incident.

**Comment by jwilsson** [comment]
I tested your code and that works just fine. I'm guessing you've tested again since yesterday? Cause it seems [Spotify had some issues](https://github.com/spotify/web-api/issues/847) with the search endpoint.

**Comment by outspokenmagazine** [comment]
I did just retest the old code, and indeed today it is not giving my any 404 responses. So you are right, it must have been an issue in regards to Spotify endpoints problems.

Thank you for looking into it anyway and of course many thanks for the package in general!
