### ISSUE TITLE
github pages links

### ISSUE THREAD

**Issue by kasperkamperman** [jwilsson/spotify-web-api-php#128]
The links on your github pages are broken and don't point to the documentation anymore. 

https://jwilsson.github.io/spotify-web-api-php/

**Comment by jwilsson** [comment]
Hi!
Yes, the documentation was moved into the main repo quite some time ago.

It's still available (without CSS though) on the Wayback Machine: https://web.archive.org/web/20160404170325/https://jwilsson.github.io/spotify-web-api-php/.
