### ISSUE TITLE
Changes to playlist URIs

### ISSUE THREAD

**Issue by PouleR** [jwilsson/spotify-web-api-php#131]
See the following blogpost: https://developer.spotify.com/community/news/2018/06/12/changes-to-playlist-uris/

API Endpoints will change for playlists and also the playlist URIs will be changed in a way that the userid is not present anymore.

**Comment by PouleR** [comment]
Great job! Thanks a lot

**Comment by jwilsson** [comment]
I just released new methods in `2.5.0`, deprecating the ones accepting `$userId`.

Just a heads up though, `SpotifyWebAPI::createPlaylist()` doesn't work right now due to an error on Spotify's end. Tracking it here: https://github.com/spotify/web-api/issues/936

**Comment by bih** [comment]
Just to inform you @jwilsson - as this was referenced to spotify/web-api#936 - that we have now resolved this issue. See the comment in the issue for more details :)

**Comment by jwilsson** [comment]
I just pushed `2.5.1` using the correct endpoint.

Thanks for the update @bih!
