### ISSUE TITLE
I can't delete the playlist tracks by position

### ISSUE THREAD

**Issue by raulojeda22** [jwilsson/spotify-web-api-php#132]
I want to delete all the tracks of a playlist and I have a code more or less like this:

```
$playlist=$this->api->getUserPlaylist($userId,$playlistId);
$snapshotId=$playlist->snapshot_id;
while ($snapshotId){
 $tracks = [ 0 ];
 $snapshotId=$this->api->deletePlaylistTracks($playlistId, $tracks, $snapshotId);
}
```
But it outputs the error: JSON body doesn't conform to specification

```
I've also tried using:
$tracks= [
'positions' => 0
];
```
But it outputs the error: Missing or invalid positions

Expected behaviour:
I want to remove the first track of the playlist until $snapshotId becomes false (the playlist is empty)

**Comment by jwilsson** [comment]
Hi!
`positions` needs to be an array too, so this should work:

```php
$playlist=$this->api->getUserPlaylist($userId,$playlistId);
$snapshotId=$playlist->snapshot_id;
while ($snapshotId){
  $tracks = [
    'positions' => [0]
  ];
   
  $snapshotId=$this->api->deletePlaylistTracks($playlistId, $tracks, $snapshotId);
}
```

I think though, in this case `replacePlaylistTracks` might be a better fit. That is, if you only want to clear a playlist. That will be quicker and a `$snapshotId` will always be returned from `deletePlaylistTracks`, even when the playlist is empty.

An example using `replacePlaylistTracks`:
```php
$this->api->replacePlaylistTracks($playlistId, []);
```

Passing an empty list of tracks will clear the whole playlist in one go.

Hope this helps!

**Comment by raulojeda22** [comment]
Hi Jwilsson! Thanks for the quick reply. In this case replacePlaylistTracks made the job for me, unfortunately using positions as an array also failed with the message:
"Could not remove tracks, please check parameters."

I'm not sure why this happens, so I will leave it to you. When you find the solution you could update the the managing-user-playlists.md file in the "Delete tracks from a user's playlist based on positions" sections since it doesn't fit the correct answer. I think that more or less would end up like this:

It would change from this:
$trackPositions = [
    5,
    12,
];
$api->deletePlaylistTracks('USER_ID', 'PLAYLIST_ID', $trackPositions, 'SNAPSHOT_ID');

To more or less this:
$trackPositions = [
    'positions' => [5,12]
];
$api->deletePlaylistTracks('PLAYLIST_ID', $trackPositions, 'SNAPSHOT_ID');

I was a bit confused at the beginning because this example didn't matched the definition of the method in SpotifyWebAPI.md: "Or an array with the key "positions" containing integer positions of the tracks to delete."

Just wanted to say, thanks a bunch for your time and your help!
