### ISSUE TITLE
How to install *without* composer?

### ISSUE THREAD

**Issue by pkiula** [jwilsson/spotify-web-api-php#134]
For various reasons, we need to include the files without Composer etc. Just the code. Simple PHP. Where can I find the docs on how to just copy a folder, and include/require the right files? Not `vendor/autoload.php` but some actual file in the src. Thanks!

**Comment by jwilsson** [comment]
Hi!
Installing without Composer isn't "officially" supported, but if wanna do it anyway you'll need to include every file in the `src` folder. Don't forget `cacert.pem`, just put that in the same folder as the rest and everything should work.

**Comment by andersborgabiro** [comment]
I did it this way:

A folder called "spotify" containing the includes and cacert.pem.

Referring to them via:

    require 'spotify/SpotifyWebAPI.php';
    require 'spotify/SpotifyWebAPIException.php';
    require 'spotify/Request.php';
    require 'spotify/Session.php';
