### ISSUE TITLE
Is it possible to reorder more than one track at a time?

### ISSUE THREAD

**Issue by ilitotor** [jwilsson/spotify-web-api-php#135]
Can I reorder, for example, 10 tracks at a time? 
Put the last 10 track in the first positions?

Or just one by one? 

thanks.

**Comment by ilitotor** [comment]
Hi, thanks for the quick response!

But, if I wanna put 10 tracks which are in non-sequential positions, in first?

For example: put track 4, 9, 13 in first. Or put in first 15, 9, 7, 11.

I tried to create a loop, but obviously, with each loop, the positions had already changed.

Is there a way to put an array first?

Thanks,

**Comment by jwilsson** [comment]
Aha, I see. It [doesn't look](https://developer.spotify.com/documentation/web-api/reference/playlists/reorder-playlists-tracks/) like it's possible to pass an array though.

But shouldn't you be able to solve it by using a loop? Something along the lines of updating `range_start` and/or `insert_before` on each iteration?

**Comment by jwilsson** [comment]
Or on second thought, perhaps `SpotifyWebAPI::replacePlaylistTracks()` could be used together with `SpotifyWebAPI::getPlayListTracks()`. 

For example, getting all the tracks, reordering them, and then replacing the whole playlist.

```php
$tracks = $api->getPlayListTracks('PLAYLIST_ID');

// Do some magic reordering...

$api->replacePlaylistTracks('PLAYLIST_ID', $reorderedTracks);
```

**Comment by ilitotor** [comment]
Amazing!

I will try this approach!

Thanks a lot

**Comment by ilitotor** [comment]
Amazing!

I will try this approach!

Thanks a lot
