### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by hbravocrp** [jwilsson/spotify-web-api-php#138]
Problem 1
    - Can only install one of: jwilsson/spotify-web-api-php[2.5.0, dev-master].
    - Can only install one of: jwilsson/spotify-web-api-php[2.5.1, dev-master].
    - Installation request for jwilsson/spotify-web-api-php dev-master -> satisfiable by jwilsson/spotify-web-api-php[dev-master].
    - Installation request for jwilsson/spotify-web-api-php ^2.5 -> satisfiable by jwilsson/spotify-web-api-php[2.5.0, 2.5.1].

Installation failed, reverting ./composer.json to its original content.

**Comment by adamazad** [comment]
I've come across this, and this [answer on SO](https://stackoverflow.com/a/49458149/2151050) helped

**Comment by jwilsson** [comment]
Hi!
Did @adamazad's reply help you?

If not, we need some more info. What are you trying do to? 

* Installing it through Composer?
* Which command are you using in that case?
* Is the library already listed in your `composer.json`?
