### ISSUE TITLE
Authorize endpoint is wrong, results in "access_denied"

### ISSUE THREAD

**Issue by lu3do** [jwilsson/spotify-web-api-php#143]
Since yesterday (november 6th) I was having issues with authorizing new users.
Every request returned "result=access_denied"
Turns out the endpoint used in `getAuthorizeUrl()` was not correct.

The endpoint should be without the trailing slash.
`https://accounts.spotify.com/authorize?`
and not
`https://accounts.spotify.com/authorize/?`

This did work before november 6th, but I guess they changed something in the Spotify API.

See: 
https://twitter.com/SpotifyPlatform/status/1059932726395133952
https://twitter.com/SpotifyPlatform/status/1059932376011337737
https://developer.spotify.com/documentation/general/guides/authorization-guide/#authorization-code-flow

**Comment by jwilsson** [comment]
Oh, that's not good! 😬 

I'll push a patch later tonight (CET).

**Comment by jwilsson** [comment]
I've just published `2.6.1` with the correct URL.
