### ISSUE TITLE
" Invalid authorization code" issue on Mobile (Android)

### ISSUE THREAD

**Issue by lu3do** [jwilsson/spotify-web-api-php#145]
Since this month (exactly November 1st) I'm receiving a high number of " Invalid authorization code" coming from mobile users.

I'm aware of the recent issue with the wrong authentication endpoint.
https://github.com/jwilsson/spotify-web-api-php/issues/143
But this seems to be a different issue.

It seems to happen mostly on mobile devices running on Android, and almost all of them using Chrome mobile.
![xnqo8fmj](https://user-images.githubusercontent.com/482346/49192454-0143cb00-f330-11e8-9296-62fdc99b7abe.jpg)

I actually contacted the Spotify developers first, but they told me to open a issue here.

**Comment by jwilsson** [comment]
Hmm, I have no idea what could be causing that. Have you been able to reproduce it? Do you know of any other changes to your tech stack that happened around November 1? Are you using some PHP framework etc.?

If we can find the cause and it's something in this library, I'll of course be happy to fix it/accept a PR fixing it. But for now, I'm at a loss

**Comment by jwilsson** [comment]
Closing this due to a lack of activity.
