### ISSUE TITLE
Unauthorized

### ISSUE THREAD

**Issue by GK-Coding** [jwilsson/spotify-web-api-php#146]
I keep getting an error saying the following
Fatal error: Uncaught SpotifyWebAPI\SpotifyWebAPIException: Unauthorized.
What could be the problem?

**Comment by jwilsson** [comment]
Hi!
We're gonna need some more to go on. The error indicates your API calls aren't properly authorize, due to a missing access token, an expired access token, etc.

Can you show the code you're using?

**Comment by GK-Coding** [comment]
The auth.php is as follows.
`
   
    <?php

    session_start();

    require 'backend/dbh.inc.php';
    require 'vendor/autoload.php';

    $session = new SpotifyWebAPI\Session(
        'Id',
        'Secret'
    );

    $session->requestCredentialsToken();
    $accessToken = $session->getAccessToken();
    $sql = "UPDATE users SET token = '$accessToken', tokentimestamp = CURRENT_TIMESTAMP WHERE id = '$_SESSION[id]'";
    mysqli_query($conn, $sql);

    // Store the access token somewhere. In a database for example.

    // Send the user along and fetch some data!
    header('Location: dashboard.php');
    die();`
The dashboard file where the api token is set is the following.
`
    
    session_start();
    require 'backend/dbh.inc.php';
    require 'vendor/autoload.php';

    if (!isset($_SESSION['id'])) {
        header("Location: signup.php");
        exit;
    }
    $sqldeletetoken = "UPDATE users SET token = '' WHERE tokentimestamp < DATE_SUB(NOW(), INTERVAL 50 MINUTE)";
    mysqli_query($conn, $sqldeletetoken);
    $sqluser = "SELECT * FROM users WHERE id = '$_SESSION[id]'";
    $resultuser = mysqli_query($conn, $sqluser);
    $rowuser = mysqli_fetch_assoc($resultuser);
    $token = $rowuser['token'];

    if (!empty($token)) {
        $api = new SpotifyWebAPI\SpotifyWebAPI();
        $api->setAccessToken($token);
    } else {
        header("Location: auth.php");
        exit;
    }`

**Comment by GK-Coding** [comment]
I switched to Authorization Code Flow and it worked
