### ISSUE TITLE
SpotifyWebAPIException: cURL transport error: 35 Encountered end of file in /var/app/current/public/vendor/jwilsson/spotify-web-api-php/src/Request.php:215

### ISSUE THREAD

**Issue by csimpi** [jwilsson/spotify-web-api-php#147]
Hi, I'm randomly getting this error message.
When I catch the `SpotifyWebAPIException` and trying to get the error code, I'm getting error code 0 and the message is below:
`SpotifyWebAPI\SpotifyWebAPIException: cURL transport error: 35 Encountered end of file in /var/app/current/public/vendor/jwilsson/spotify-web-api-php/src/Request.php:215`

**Comment by jwilsson** [comment]
Hi!
It looks like something with the TLS communication to Spotify is wrong. How are you running your app? Behind a proxy or something similar?

**Comment by csimpi** [comment]
Hi, thank you for your answer!
Yes, this is happening when I'm testing on AWS Elastic Beanstalk only, on my local I've never got this error.

**Comment by jwilsson** [comment]
Hmm, I found [this issue](https://github.com/googleapis/google-cloud-php/issues/91) which looks like the same type of error. Using some of the steps from there could you try adding these lines to the cURL options array here: https://github.com/jwilsson/spotify-web-api-php/blob/4937bd7fd8edd132debdf5ba49ca8cf4c50a1fe7/src/Request.php#L174

```php
$options = [
  ...
  CURLOPT_IPRESOLVE => CURL_IPRESOLVE_V4,
  CURLOPT_SSLVERSION => CURL_SSLVERSION_TLSv1_2, // And try with CURL_SSLVERSION_TLSv1_1 as well (not really recommended, but just to try to narrow it down)
];
```

Could you try some combinations of those options and see what happens? Thanks!

**Comment by csimpi** [comment]
Hi thank you, I'll try them and let you know the results, I'm really glad you are trying to help me out :)

**Comment by jwilsson** [comment]
Closing this due to a lack of activity.
