### ISSUE TITLE
Tutorial for a noob please?

### ISSUE THREAD

**Issue by ChrisBlackCH** [jwilsson/spotify-web-api-php#149]
Dear everyone!

I am very new with the spotify api. I followed this link after I had a good read, but I am not very familiar with how can I achieve a couple of functions.

I am happy and ready to pay for someone's time to help me achieve on how to increase followers on a playlist via this spotify api.

Unless it is not possible to use this api for such function!

Please let me know,
Chris Black

**Comment by adamazad** [comment]
Are you working on an social media website? I've implemented the playlist
follow for a client recently. We can have a chat about this if you wish.

**Comment by ChrisBlackCH** [comment]
yes I am on facebook! Let's chat about it in depth please!

**Comment by ChrisBlackCH** [comment]
my facebook page is https://www.facebook.com/ChristosMavridisUK

**Comment by adamazad** [comment]
I meant to ask if you're working on a website that offers boosts on social
platforms. Sorry for the confusion.

You can email me: adam(at)adamazad(dot)com

**Comment by ChrisBlackCH** [comment]
email sent! Please check!

**Comment by ChrisBlackCH** [comment]
hi man, you never got back to me on my email. Are you still interested in helping me with this project, or shall I seek aid somewhere else?

Thanks

**Comment by adamazad** [comment]
Chris, I replied on the same day you emailed me. Could you check your spam folder?

**Comment by ChrisBlackCH** [comment]
Ohh man! got it yes! 

Ok I removed it from spam!

I will reply shortly!

**Comment by jwilsson** [comment]
Looks like you got this covered so I'm going to close this one, but feel free to keep discussing here.

Thanks for helping out @adamazad!
