### ISSUE TITLE
getUserPlaylists() doesn't return restored playlists

### ISSUE THREAD

**Issue by happy-sadan** [jwilsson/spotify-web-api-php#151]
**getUserPlaylists()** doesn't seem to return restored deleted playlists, while the Spotify console clearly does. Any fix/workaround ?

**Comment by jwilsson** [comment]
Hi!
That sounds really strange, it's the same call being made. Have you granted the same scopes to your PHP app and the console? And are you using some limit/offset in one place and not the other?

**Comment by happy-sadan** [comment]
Actually, I noticed **getUserPlaylists()** only displays non-restored playlists owned by the user, and not followed playlists, as opposed to the console.

I tried setting the same scopes in the console as in my app (even though none are required to get a user's playlists, but just in case), and only setting the **limit** option in both to 50 (to get all my playlists, I have less than 50), I'm still having the same problem.

I also tried restoring other random deleted playlists, and saw the same problem.

**Comment by jwilsson** [comment]
Hmm. If you request it using cURL straight from the command line, what do you get back then? I think the console shows the cURL command, right?

**Comment by happy-sadan** [comment]
Yes it does, doing that I also get to see my restored and followed playlists.

**Comment by jwilsson** [comment]
Thanks for working this one through with me! This is really strange, but I'll take a closer look tonight.

**Comment by jwilsson** [comment]
Okay, I think I've found the issue. When restoring a deleted playlist, it's always set to private. No matter the previous visibility of it. 

I managed to get a list of my restored playlists using `getUserPlaylists()` and through the console when requesting the `playlist-read-private` scope but not without it. If I were you, I'd open an issue on https://github.com/spotify/web-api since this doesn't seem to be an issue with this library.

**Comment by happy-sadan** [comment]
Alright, so it seams I was wrong about the scopes I set for the OAuth token in the console, sorry about that 😕

But I had read while looking for a solution that Spotify never deletes playlists, it just sets them as private and makes you unfollow them, so the only way to access them is through the account page, which explains why.

[I posted on Spotify's forum](https://community.spotify.com/t5/forums/postpage/board-id/002), since it seems like more of a problem with Spotify itself rather than it's API, and also since they hardly seem active over there.
