### ISSUE TITLE
Callback for $api->updatePlaylistImage

### ISSUE THREAD

**Issue by anderthalb** [jwilsson/spotify-web-api-php#152]
Hi,

is there a way to know exactly when the Image is uploaded and ready for `$api->updatePlaylistImage`? 

I create a playlist, upload a cover and add tracks to it and then I redirect the user to this fresh playlist. But when he enters the playlist, the cover is not uploaded/saved yet. 

Thanks in advance and Cheers, Christian

**Comment by jwilsson** [comment]
Hey!
Not that I'm aware of, I'm afraid. You could ask the Spotify folks to add one over at https://github.com/spotify/web-api.

**Comment by jwilsson** [comment]
Closing this due to a lack of activity.
