### ISSUE TITLE
All playlist songs

### ISSUE THREAD

**Issue by BlockLabTV** [jwilsson/spotify-web-api-php#153]
With [this endpoint](https://github.com/jwilsson/spotify-web-api-php/blob/master/docs/examples/managing-user-playlists.md#getting-all-tracks-in-a-playlist) I only got I think the first 50 songs in the given playlist. Is there either a possibility to change the amount of songs I want to get or add an offset to the request to be able iterate over the playlist?

**Comment by jwilsson** [comment]
Hi!
It's possible to both add an offset and request more than 50 tracks at a time (I think the limit is 100). For example: 

```php
$tracks = $api-> getPlaylistTracks('PLAYLIST_ID', [
  'limit' => 100,
  'offset' => 100,
]);
```

All options are also documented here: https://github.com/jwilsson/spotify-web-api-php/blob/master/docs/method-reference/SpotifyWebAPI.md#getplaylisttracks
