### ISSUE TITLE
Access to "reason" in SpotifyWebAPIException when working with player

### ISSUE THREAD

**Issue by mengidd** [jwilsson/spotify-web-api-php#155]
When working with the [player](https://developer.spotify.com/documentation/web-api/reference/player/) and Spotify returns an error, a [reason string](https://developer.spotify.com/documentation/web-api/reference/object-model/#player-error-reasons) is included in the response. It would be super handy to get access to this reason string through the SpotifyWebAPIException exception, with for instance `$e->getReason()`. This would make it much easier to deal with the different errors. 

The reason string is available in the response body with the key `reason` on player errors.

If this is something you might consider I don't mind submitting a PR for it.

**Comment by jwilsson** [comment]
Cool, I didn't know about that property!

A PR adding a `getReason` method would be highly appreciated!
