### ISSUE TITLE
Invalid authorization code

### ISSUE THREAD

**Issue by csimpi** [jwilsson/spotify-web-api-php#158]
Hi guys,
I don't know what's happening, but I started to get `Invalid authorization code` error messages during Spotify login. I have no idea why. Is this due to something change in Spotify API?

I'm still getting the `code` paramter. I pass the parameter to the `requestAccessToken()` function, every request parameter looks good, but I'm still getting `Invalid authorization code` in the response.

Redirect URI has been added to the app's whitelisted uri's.

![image](https://user-images.githubusercontent.com/6192067/59101491-fcaf2f00-88dd-11e9-81ab-3bb40ca1893f.png)

**Comment by csimpi** [comment]
Update: The same code works only if the redirect URI's domain ends with `.com`.
It doesn't work with my local domain (vagrant.xy.loc), 
it doesn't work event with https:// public domain https://xy.localtunnel.me

The redirect URIs are whitelisted of course.

**Comment by jwilsson** [comment]
This sounds like something at Spotify's end. I'd file an issue over at https://github.com/spotify/web-api and see if they can help.

**Comment by csimpi** [comment]
@csimpi you're totally right, I should have close this at my previous comment, thank you for your answer again!
