### ISSUE TITLE
custom curl options by user

### ISSUE THREAD

**Issue by csimpi** [jwilsson/spotify-web-api-php#159]
Hi,
thx for your awesome work!

I'd like to set some curl options. I can't change `Request.php` in the `vendor` folder for obvious reason.
Is it possible to set/overwrite the `$options` array from my code? If it's not it would be an awesome (and must-have) feature.

Currently, I'm getting timeout error messages randomly when I'm connecting to api.spotify.com, I'd need to set the curl connection timeout option and fine-tune the request-response frequency.

**Comment by csimpi** [comment]
A quick workaround, using Guzzle instead of curl with this adapter:
https://github.com/andig/spotify-web-api-extensions

**Comment by jwilsson** [comment]
Hey!
Sorry for the late answer!

Sounds like a valid use case, I'll take a look at it over the weekend.

**Comment by csimpi** [comment]
@jwilsson 
Thank you!
I think the best way would be making an adapter for the curl part with an opportunity to use any kind of external HTTP Clients.

Also, I'd recommend using Guzzle instead of curl. Curl has a lot of problems on several servers, lots of memory leaking problems, etc. Now that I have overridden the Request class and using Guzzle HTTP every other random issue has been disappeared (even behind a proxy).

**Comment by jwilsson** [comment]
@csimpi Absolutely, I agree! It's definitely something I've thought about and will look into for the next major release.
