### ISSUE TITLE
Web Playback SDK To Play Songs In Browser

### ISSUE THREAD

**Issue by mohammedjammeh** [jwilsson/spotify-web-api-php#164]
Hey there,

I was wondering if this API offers the feature to control Spotify's [Web Playback SDK Quick Start](https://developer.spotify.com/documentation/web-playback-sdk/quick-start/#). 

I looked at the [Controlling User Playback](https://github.com/jwilsson/spotify-web-api-php/blob/master/docs/examples/controlling-user-playback.md) section but it seems like it only shows the controls for the playback.

I got the SDK working with JavaScript but it's not perfect. Also, it does say in the [documentation](https://developer.spotify.com/documentation/web-playback-sdk/quick-start/#) that `To play a track inside your browser, connect to the Web Playback SDK Quick Start Player player in another Spotify client` so I'm wondering if I just have to create another client to make it work properly. 

Anyway, I would appreciate it if you could clarity this.

Thank you.

**Comment by jwilsson** [comment]
Hi!
I'm afraid I can't be of much assistance. I've never used the Web Playback SDK but after looking through the Quick Start real quick it sounds like you should be able to connect to it through the methods listed on the [Controlling User Playback](https://github.com/jwilsson/spotify-web-api-php/blob/master/docs/examples/controlling-user-playback.md) page.

The `$api->getMyCurrentPlaybackInfo()` should give you the ID of your Web Playback SDK player and then calling `$api->play()` will hopefully start playing something on your web page.

**Comment by mohammedjammeh** [comment]
Not a problem, that's absolutely fine. I will keep playing around with it and should be able to figure it. Also, thanks for creating this package. It has been very useful for my university and personal projects. I will go ahead and close this ticket for now.

**Comment by shahzeb1** [comment]
You can control the web player by:

1. Looking at a user's devices
2. Finding the `deviceId` for the web front end
3. Doing a `::play()` api call with the device set to the browser
