### ISSUE TITLE
Invalid Redirect URI

### ISSUE THREAD

**Issue by bfblackjack** [jwilsson/spotify-web-api-php#170]
I created a new app  with my Spotify account and am now attempting to test the authentication via auth code method. Unfortunately, I keep getting an "Invalid Redirect URI" error from Spotify. I have confirmed that my URLs (HTTP & HTTPS!) are in the app settings and I have confirmed, passing both statically and dynamically, the URL passed into the session redirectUri is the same. I am at a loss for words. Is there something easy I am missing or what?

**Comment by jwilsson** [comment]
Hey!
I don't know what to tell you, some people just seem to experience these issues with no logical explanation (it has happened to me too). Deleting the app and creating a new one fixes it sometimes but otherwise I'm afraid I'm at a loss for words too.

**Comment by bfblackjack** [comment]
Interestingly enough, it appears to be working now. Go figure - nothing changed on my end since this post. Hmmm!
