### ISSUE TITLE
Can you write a more accurate tutorial about the auto-refreshing token?

### ISSUE THREAD

**Issue by DarkFighterLuke** [jwilsson/spotify-web-api-php#172]
I have not clear in mind how the auto-refresh mechanism works and how to use it.
Can you help me?

Maybe the tips given here can be useful to feed the relative documentation page

**Comment by jwilsson** [comment]
Hi!
Absolutely, I'd be happy to! What do you think is missing right now?

**Comment by DarkFighterLuke** [comment]
I think the code snippets should be more complete. I mean, maybe you can write some other lines of code where at the moments there are comments, making the examples awesome.

Furthermore, I have not really clear how to work with an existing refresh token. So, I haven't at the moment any token in the database: is it necessary to follow that part if I set the autorefresh option since the first login?

Thanks for your timely response!

**Comment by jwilsson** [comment]
Cool! I'll look over the code examples and try co clarify some other things as well.

I can answer your second question right now though. As long has you have a valid refresh token you don't need an access token. Set `auto_refresh` to `true` and it'll fetch a new access token for you.

**Comment by DarkFighterLuke** [comment]
Thank you @jwilsson !

Nice project! ;)
