### ISSUE TITLE
no preview_urls with authorization using the client credentials flow

### ISSUE THREAD

**Issue by cdlx23** [jwilsson/spotify-web-api-php#173]
Hi :)
First of all thanks a lot for the wrapper, I love it and it's very useful to me!

For some reason I don't get the preview_urls for tracks with authorization using the client credentials flow. Using the authorization code flow it works fine. All other values like id, popularity etc. work just fine, just preview_url is empty. I tested it with getTrack(s) and getAlbum(s) Any idea what this could be?

Example request:

`$track = $api->getAlbum( '3msNbiI057b6ypzeOTjgxJ', [
      'market' => 'de'
    ] );`

Thanks a lot!!

**Comment by jwilsson** [comment]
Hey!
Thank you for the kind words! :)

[According to Spotify](https://github.com/spotify/web-api/issues/729#issuecomment-349758014) the `preview_url` field can be `null` for a variety of reasons. My guess is that you need a user's info to see the `preview_url` values.
