### ISSUE TITLE
getTrack Fatal Error with Partial Track

### ISSUE THREAD

**Issue by thejames76** [jwilsson/spotify-web-api-php#176]
I'm mucking about with the wrapper and found that a partial getTrack call is resulting in a Fatal Error. I was expecting a FALSE condition being returned. Is this expected?

Using a full / complete track ID returns the Track's object as expected.

To test I ran this:

`$sid = $api->getTrack("fjdkfds");`

Fatal error: Uncaught SpotifyWebAPI\SpotifyWebAPIException: invalid id in <REMOVED>/spotify/vendor/jwilsson/spotify-web-api-php/src/Request.php:40 Stack trace: #0 <REMOVED>/spotify/vendor/jwilsson/spotify-web-api-php/src/Request.php(242): SpotifyWebAPI\Request->parseBody(Object(stdClass), 400) #1 <REMOVED>/spotify/vendor/jwilsson/spotify-web-api-php/src/Request.php(121): SpotifyWebAPI\Request->send('GET', 'https://api.spo...', '', Array) #2 <REMOVED>/spotify/vendor/jwilsson/spotify-web-api-php/src/SpotifyWebAPI.php(72): SpotifyWebAPI\Request->api('GET', '/v1/tracks/*fds...', Array, Array) #3 <REMOVED>/spotify/vendor/jwilsson/spotify-web-api-php/src/SpotifyWebAPI.php(83): SpotifyWebAPI\SpotifyWebAPI->sendRequest('GET', '/v1/tracks/*fds...', Array, Array) #4 <REMOVED>/spotify/vendor/jwilsson/spotify-web-api-php/src/SpotifyWebAPI.php(1278): SpotifyWebAPI\SpotifyWebAPI->sendRequest('GET', '/v1/tracks/*fds...', Array, Ar in <REMOVED>/spotify/vendor/jwilsson/spotify-web-api-php/src/Request.php on line 40

**Comment by jwilsson** [comment]
Hi!
Yes, that's expected because Spotify returns an error response which is then converted to a PHP exception. Nothing is currently done to differentiate between different kinds of errors.

**Comment by thejames76** [comment]
okay, thanks for the info. <3
