### ISSUE TITLE
Vagueness in device id.

### ISSUE THREAD

**Issue by shahzeb1** [jwilsson/spotify-web-api-php#177]
Hello. First of all thank you so much for this amazing library. While using it, I was reading the [playback docs](https://github.com/jwilsson/spotify-web-api-php/blob/master/docs/examples/controlling-user-playback.md) and I noticed that it isn't quite  clear where`$deviceId` is coming from. 

If this is a simple fix, I will gladly create a PR if you tell me what end-point can help gather $deviceId.

**Comment by jwilsson** [comment]
Hi!
Thank you!

The `SpotifyWebAPI::getMyDevices()` method can be used to get a list of the available devices. I'm thinking a "Getting the user's devices" (or similar) section at the top should do the trick? I'd be more than happy to merge a PR for it if you're interested!

**Comment by shahzeb1** [comment]
Cool. Consider this something that I will go ahead and work on. Will ping back within a day or so.
