### ISSUE TITLE
[Question] About refresh token

### ISSUE THREAD

**Issue by foremtehan** [jwilsson/spotify-web-api-php#181]
Am i doing it right ? I want to refresh access token when it expires, Does it refresh token for every api call ? :

```php
    /**
     * Spotify constructor.
     */
    public function __construct()
    {
        $this->api = $this->getToken();
    }

    private function getToken()
    {
        $session = new Session(
            'CLIENT_ID',
            'SECRET_ID',
        );

        $api = new SpotifyWebAPI();

        $api->setSession($session);
        $api->setOptions([
            'auto_refresh' => true,
        ]);

        $session->refreshAccessToken('refresh_token');

        $newAccessToken  = $session->getAccessToken();
        $newRefreshToken = $session->getRefreshToken();

        $session->setAccessToken($newAccessToken);
        $session->setRefreshToken($newRefreshToken);

        return $api;
    }

```

**Comment by jwilsson** [comment]
Hey!
Yes, that code will refresh the access token automatically when it detects an expired one.

Some parts of your code isn't needed though and I recommend you to store the (possibly new) access and refresh tokens somewhere (like a database or session). I'd rewrite it like this:

```php
    /**
     * Spotify constructor.
     */
    public function __construct()
    {
        $this->api = $this->getToken();
    }

    private function getToken()
    {
        $session = new Session(
            'CLIENT_ID',
            'SECRET_ID',
        );

        // Fetch previously requested tokens and set them on the Session instance here

        if ($oldAccessToken && $oldRefreshToken) {
            $session->setAccessToken($oldAccessToken);
            $session->setRefreshToken($oldRefreshToken);
        }

        $api = new SpotifyWebAPI();

        $api->setSession($session);
        $api->setOptions([
            'auto_refresh' => true,
        ]);

        $newAccessToken  = $session->getAccessToken();
        $newRefreshToken = $session->getRefreshToken();

        // Store the new tokens somewhere else here

        return $api;
    }
```

Hope this helps!

**Comment by foremtehan** [comment]
@jwilsson thanks! But i dont understand this part :

`if ($oldAccessToken && $oldRefreshToken)` If i store this old tokens somewhere else the if condition always be true, Should i check the tokens before condition?

**Comment by jwilsson** [comment]
@foremtehan No, you don't need to check the expiration. It'll refresh them if needed. You can skip the ìf` statement if you're sure you'll always have something stored (they're not being null).

**Comment by u20200522** [comment]
Hi @foremtehan and @jwilsson sorry to ask follow up questions on a closed issue.

I wondered how I could implement the code detailed in this issue into my simple application - e.g. say I have this simple code to run a search:

```
/*
-- I am keeping a record of current accessToken and refreshToken ass session variables
-- set in the callback.php file like this:

$accessToken = $session->getAccessToken();
$refreshToken = $session->getRefreshToken();

// Starting session
if(!isset($_SESSION)) { session_start(); }
$_SESSION["accessToken"] = $accessToken;
$_SESSION["refreshToken"] = $refreshToken;
*/

$session = new SpotifyWebAPI\Session(
	'CLIENT_ID',
	'SECRET_ID'
);

$session->requestCredentialsToken();
$accessToken = $session->getAccessToken();

$options = ['return_assoc' => true];
$api = new SpotifyWebAPI\SpotifyWebAPI($options);
$api->setAccessToken($accessToken);
$search = $api->search('fugazi','album');
```

I am not sure how I'd change my code to plug in the code that's used on this issue to refresh the access token automatically when it detects an expired one?

Sorry to be asking very basic questions. I realise I need to refresh the accessToken and have read the [relevant doc](https://github.com/jwilsson/spotify-web-api-php/blob/9063d2f18934319b71393fb1780de32d45897df9/docs/examples/refreshing-access-tokens.md) but am still stuck.

Thanks!
