### ISSUE TITLE
Searching in an artist's albums

### ISSUE THREAD

**Issue by foremtehan** [jwilsson/spotify-web-api-php#182]
There seems to be no way to find an album from specific artist in spotify api endpoint, For example i want to find the Pink [album](https://open.spotify.com/album/7x5NKhqh2UaVMETCkTpjab) from Ferry Corsten, We have two choice, Grab all album from the artist then search into it Or search album and get All results (for that album there is 4885 result item!), So is there a proper way to do this by this repo?

**Comment by jwilsson** [comment]
Hey!
It should be possible to use the `SpotifyWebAPI::search()` method and combining what Spotify calls "field filters" into a query. Take a look at [this example](https://developer.spotify.com/console/get-search-item/?q=album%3Aarrival+artist%3Aabba&type=album) and [their docs](https://developer.spotify.com/documentation/web-api/reference/search/search/#writing-a-query---guidelines).

The code could for example look like:

```php
$api->search('album:pink artist:"Ferry Corsten"', 'album');
```
