### ISSUE TITLE
Feature request: support shows & episodes API

### ISSUE THREAD

**Issue by andrisi** [jwilsson/spotify-web-api-php#183]
I tried it and it does work, so it would be nice to have support for the undocumented shows and episodes API described at: https://github.com/spotify/web-api/issues/551#issuecomment-583748908 Thanks!

**Comment by jwilsson** [comment]
Hey!
Thanks for the suggestion!

I'd rather not add things that aren't officially supported, though. But I'll leave this open to implement it if/when it's officially supported.

**Comment by jwilsson** [comment]
Official support for this is available in `3.2.0` 🎉
