### ISSUE TITLE
Invalid authorization code

### ISSUE THREAD

**Issue by moseleyi** [jwilsson/spotify-web-api-php#188]
I wanted to try out this library and copied the code from the documentation page but upon refreshing my script I'm getting:

```Uncaught SpotifyWebAPI\SpotifyWebAPIAuthException: Invalid authorization code```

Do I need to do anything specific to get this to work?

**Comment by jwilsson** [comment]
Hey!
Is the `code` parameter present in the URL between page loads? It's only valid once. Try to remove it before reloading the page.
