### ISSUE TITLE
Audio Analysis not Working

### ISSUE THREAD

**Issue by MadalenaSousa** [jwilsson/spotify-web-api-php#190]
Hi!
I was trying to use the getAudioAnalysis feature and soometimes it works and sometimes I get this error: Uncaught SpotifyWebAPI\SpotifyWebAPIException: analysis not found in ..\vendor\jwilsson\spotify-web-api-php\src\Request.php:45

I don't understand why it sometimes works and sometimes it doesn't. But this has been happening more and more frequently.What can I do? Any sugestions on what I might be doing wrong?

Here is the full error: 
Fatal error: Uncaught SpotifyWebAPI\SpotifyWebAPIException: analysis not found in ..\vendor\jwilsson\spotify-web-api-php\src\Request.php:45 Stack trace: #0 ..\vendor\jwilsson\spotify-web-api-php\src\Request.php(254): SpotifyWebAPI\Request->parseBody(Object(stdClass), 404) #1..\vendor\jwilsson\spotify-web-api-php\src\Request.php(126): SpotifyWebAPI\Request->send('GET', 'https://api.spo...', '', Array) #2 ..I\vendor\jwilsson\spotify-web-api-php\src\SpotifyWebAPI.php(76): SpotifyWebAPI\Request->api('GET', '/v1/audio-analy...', Array, Array) #3 ..\vendor\jwilsson\spotify-web-api-php\src\SpotifyWebAPI.php(713): SpotifyWebAPI\SpotifyWebAPI->sendRequest('GET', '/v1/audio-analy...') #4 ..\php\getTracksInfo.php(24): SpotifyWebAPI\SpotifyWebAPI->getAudioAnalysis('4Y6GIje3GErVRIq...') #5 {main} thrown in ..\vendor\jwilsson\spotify-web-api-php\src\Request.php on line 45

**Comment by jwilsson** [comment]
Hey!
It seems like this is an issue on Spotify's end, https://github.com/spotify/web-api/issues/1570.

**Comment by MadalenaSousa** [comment]
Hum, ok, thank you!
