### ISSUE TITLE
getMyTop() don't work!

### ISSUE THREAD

**Issue by Eredasu** [jwilsson/spotify-web-api-php#192]
Hi! Like the title says, $api->getMyTop($type) don't really want to work. When I use it, i got an error on the sendRequest() !

![error](https://user-images.githubusercontent.com/32577573/81497122-b536dd00-92bc-11ea-9b5b-94037ab3475d.png)

Maybe the problem just come from me, but I'm pretty new with PHP so don't be rude ! I'm dropping my code too, if maybe I make a big mistake there. Thank's you!

![code](https://user-images.githubusercontent.com/32577573/81497231-6a699500-92bd-11ea-96b0-06d98fe5d6ad.png)

**Comment by jwilsson** [comment]
Hey!
The code looks good! However, you seem to have missed the `user-top-read` scope. Add it to the `scope` array and it should work. 

```php
$options = [
        'scope' => [
            'user-read-email',
            'user-top-read',
        ],
    ];
```

**Comment by Eredasu** [comment]
Yeah that's it! Thank's a lot!
