### ISSUE TITLE
Logout function

### ISSUE THREAD

**Issue by djansen1987** [jwilsson/spotify-web-api-php#193]
Hi, First many thanks for this module!

I was wondering if it was possible to create a logout function. Did some quick seacht and found this:

>> You want to simply logout from "spotify web api" then you should terminate your spotify session >>through clear authentication token like:
>>
>>AuthenticationClient.clearCookies(getApplication());

It may be nothing but it might also be a quick win to the module.

link to forum: [https://stackoverflow.com/questions/24408444/how-to-logout-user-from-spotify-after-authorization-and-web-api-call-is-over](https://stackoverflow.com/questions/24408444/how-to-logout-user-from-spotify-after-authorization-and-web-api-call-is-over)

**Comment by jwilsson** [comment]
Hey!
Thanks for the suggestion!

Given the other answers in that thread, I don't think it's possible for this library to handle logouts. It would be up to each user of the library to do it.
