### ISSUE TITLE
"invalid authorization code"

### ISSUE THREAD

**Issue by themcgarvie** [jwilsson/spotify-web-api-php#195]
Hello.... No matter what I do I keep getting "invalid authorization code" when returning to callback url.

Any hints on how to authenticate would be welcome :/

I am using the 'demo code', I get redirected to spotify login but when I get redirected back the above occurs.

**Comment by jwilsson** [comment]
Hey!
Probably a stupid and obvious question, but I gotta ask it anyway 😄  are you removing the `code` query string between tries? It's only valid once and will give you that error otherwise.
