### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by shon-011** [jwilsson/spotify-web-api-php#196]
H!
I would like to use spotify-web-api-php to search for music.
However, during the authentication process I am encountering the following error.

> Fatal error: Uncaught SpotifyWebAPI\SpotifyWebAPIAuthException: Invalid client in /Applications/MAMP/htdocs/php_k/vendor/jwilsson/spotify-web-api-php/src/Request.php:65 Stack trace: #0 /Applications/MAMP/htdocs/php_k/vendor/jwilsson/spotify-web-api-php/src/Request.php(265): SpotifyWebAPI\Request->parseBody(Object(stdClass), 400) #1 /Applications/MAMP/htdocs/php_k/vendor/jwilsson/spotify-web-api-php/src/Request.php(115): SpotifyWebAPI\Request->send('POST', 'https://account...', 'grant_type=clie...', Array) #2 /Applications/MAMP/htdocs/php_k/vendor/jwilsson/spotify-web-api-php/src/Session.php(186): SpotifyWebAPI\Request->account('POST', '/api/token', Array, Array) #3 /Applications/MAMP/htdocs/php_k/test.php(13): SpotifyWebAPI\Session->requestCredentialsToken() #4 {main} thrown in /Applications/MAMP/htdocs/php_k/vendor/jwilsson/spotify-web-api-php/src/Request.php on line 65

`<?php
ini_set( 'display_errors', 1 );
ini_set( 'error_reporting', E_ALL );

    require_once('vendor/autoload.php');
    $session = new SpotifyWebAPI\Session(
        '{CLIENT_ID}',
        '{CLIENT_SECRET}'
    );
    $api = new SpotifyWebAPI\SpotifyWebAPI();
    $session->requestCredentialsToken();
    $accessToken = $session->getAccessToken();
    $api->setAccessToken($accessToken);

    $result = $api->search('Retrovision', 'artist');

?>
<pre>
    <?php print_r($result) ?>
</pre>`

Please help me.

**Comment by jwilsson** [comment]
Hey!
It seems the client ID or client secret is wrong since you're getting "Invalid client" back from Spotify. I'd double check the client ID and secret or try creating a new app and use those values instead.

**Comment by shon-011** [comment]
Thanks for the reply!

I just did and I've done it!
Apparently, I made a mistake in assigning the Client ID and Client Secret with { }.

Thanks so much!
