### ISSUE TITLE
Multiple instances / sessions

### ISSUE THREAD

**Issue by brandonmcconnell** [jwilsson/spotify-web-api-php#197]
What is the best practice for having multiple simultaneous Spotify API sessions? I'd like to allow multiple users from around the web to all show what they're listening to simultaneously, which will all display simultaneously from the same dashboard. 

Do I just need to start a `new SpotifyWebAPI\Session` per user? Will that allow the app to continuously read data from their account and refresh tokens without repeated authentication so their status is publicly available? Ideally, one person should be able to see what anyone else on the platform is listening to and be able to also tune into what someone else is listening to, so there will also be two levels of sessions: (1) external sessions of all other users on the platform, and (2) the current user's internal session.

Sorry if this isn't the correct medium for a question like this. Wasn't sure where else to go.

**Comment by jwilsson** [comment]
Hey!  
Yeah, one `Session` instance per user should do the trick. Reusing the same `Session` instance could work but it would be more work updating it with the correct tokens. One per user should be easier to work with.

**Comment by brandonmcconnell** [comment]
Perfect, thanks!
