### ISSUE TITLE
Exception removing a track from a playlist

### ISSUE THREAD

**Issue by tobyink** [jwilsson/spotify-web-api-php#199]
I'm getting the following, which I guess is maybe an error in the Spotify API itself rather than this library, but who knows?

```
PHP Fatal error:  Uncaught SpotifyWebAPI\\SpotifyWebAPIException: JSON body doesn't conform to specification
```

This is thrown when I execute the following to delete a single track:

```
$api->deletePlaylistTracks( playlist_id, [ 'tracks' => [ $track_id ] ] );
```

**Comment by jwilsson** [comment]
Hey!
It seems the `id` key is missing in the `tracks` array. This should work:

```php
$api->deletePlaylistTracks( playlist_id, [ 'tracks' => [ 'id' => $track_id ] ] );
```

**Comment by tobyink** [comment]
My bad! I misinterpreted the documentation for that method and hadn't even checked the example.

Works great now. Thanks!
