### ISSUE TITLE
Refresh token should not be in Session

### ISSUE THREAD

**Issue by hvt** [jwilsson/spotify-web-api-php#20]
Just wanted to check whether you guys would agree on this, or not.

In my opinion, the `refresh_token` should not exist in the `Session` class. It should just be returned by `Session::requestToken()` (I refactored that to `Session::requestRefreshAndAccessToken()` in https://github.com/jwilsson/spotify-web-api-php/pull/19) and be supplied when the access token is refreshed.

Why? Well, at the moment it is stored in the class for convenience, but no one would be using it like this. The access token expiration takes quite long (one hour at the moment), that anyone using the refresh token should already save it somewhere persistent. By removing it from the class, it will be more obvious the refresh token is not something volatile. Plus you leave it up to the user to do something with the token or not.

Therefore, I'd like to suggest to:
* Remove `Session::$refreshToken` (plus its associated get and set methods)
* Change `Session::requestToken()` (`Session::requestRefreshAndAccessToken()` in https://github.com/jwilsson/spotify-web-api-php/pull/19) to return an array containing the three returned values (access token, expiry date, and the refresh token) and `null` when something goes wrong. 
* Change `Session::refreshToken()` (`Session::refreshAccessToken()` in https://github.com/jwilsson/spotify-web-api-php/pull/19) to have the refresh token as a parameter.

Next, something that just came to my mind: the access token's expire period also doesn't do much. I.e. it's saved, but you know nothing of it (e.g. when was the last access token retrieved). So we should either do something with it (calculate when the access token actually expires and act on it), or just leave this to the user of the class...

Just some ideas, wonder what you guys think ;].

**Comment by hvt** [comment]
Will start on this once I got some more time (probably next week or so).

**Comment by jwilsson** [comment]
Don't worry about it. I don't think we should include this until the 1.0 release anyway (and it's a while before that will happen).

**Comment by jwilsson** [comment]
@hvt you interested in taking a stab at this? Just let me know if not and I'll take care of it :)

**Comment by hvt** [comment]
@jwilsson No I haven't. You're good to fix it yourself :].

**Comment by jwilsson** [comment]
@hvt Alright, thanks for your quick response!
