### ISSUE TITLE
failed while authorizing, why error 'Invalid client' ? 

### ISSUE THREAD

**Issue by pepoper** [jwilsson/spotify-web-api-php#204]
i'am using laravel 8.0, 

code :
 $session = new SpotifyWebAPI\Session(
            '----XXXX---',
            '----XXXX----'
        );
        
        $session->requestCredentialsToken();
        $accessToken = $session->getAccessToken();

this error:
SpotifyWebAPI\SpotifyWebAPIAuthException
Invalid client

**Comment by jwilsson** [comment]
Hey!
Something seems to be wrong with your Spotify app, sometimes it helps just creating a new one and using that one instead.

**Comment by pepoper** [comment]
ridiculous case 🙃

solved, apparently because of a problem when copying the CLIENT_ID using the Chrome browser Version 85.0.4183.121, when pasting the CLIENT_ID in the text editor, the result given was different from the original.

alternative way is to use another browser when copying CLIENT_ID, in this case i'am using Mozilla
