### ISSUE TITLE
Bug with auto retry feature?

### ISSUE THREAD

**Issue by gabrielalack** [jwilsson/spotify-web-api-php#205]
Looks like rate limiting is causing an error if you have auto retry enabled
<img width="1186" alt="Screen Shot 2020-10-07 at 2 59 05 PM" src="https://user-images.githubusercontent.com/3742245/95381828-5945a400-08ae-11eb-9440-4fb6ea02ab80.png">

**Comment by gabrielalack** [comment]
Looks like the correct header to access is lowercase 'retry-after'. The library is trying to access it with caps. Here is a dump of a rate limited response
<img width="1129" alt="Screen Shot 2020-10-07 at 6 25 23 PM" src="https://user-images.githubusercontent.com/3742245/95398114-9c157500-08ca-11eb-8319-45a5a571e4ed.png">

**Comment by jwilsson** [comment]
Hey!
Yeah, that seems to be the issue. There's a fix pending which normalizes the response headers for the next major version (`4.0`) in the `next` branch. I'm afraid I don't have an ETA on a release for it right now though.

**Comment by jwilsson** [comment]
I decided to get a small temporary fix in for it. `3.6.1` should fix the issue, let me know if it doesn't!
