### ISSUE TITLE
Fatal error when invalid ID is used

### ISSUE THREAD

**Issue by samcera** [jwilsson/spotify-web-api-php#207]
When I use the error handling code (as described in the example doc and posted below) I receive a fatal error (posted below as well). Judging from issue #176 it seems that this is expected behavior for invalid ID's. However, if that's the case I don't seem to understand what the code below does. It's not showing me a echoed 404 in the response (or in the headers). Is this still expected behavior for invalid ID's or am I missing something here? I intended to check if the ID I use to call Spotify is valid, before proceeding with the other code. Any help is greatly appreciated :)  

```
try {
    $track = $api->getTrack('non-existing-track');
} catch (SpotifyWebAPIException $e) {
    echo 'Spotify API Error: ' . $e->getCode(); // Will be 404
}
```

 ```
Fatal error: Uncaught SpotifyWebAPI\SpotifyWebAPIException: non existing id in C:\wamp\www\test\vendor\jwilsson\spotify-web-api-php\src\Request.php on line 56
( ! ) SpotifyWebAPI\SpotifyWebAPIException: non existing id in C:\wamp\www\test\vendor\jwilsson\spotify-web-api-php\src\Request.php on line 56
Call Stack
#	Time	Memory	Function	Location
1	0.0019	413544	{main}( )	...\app.php:0
2	0.0033	430200	SpotifyWebAPI\SpotifyWebAPI->getTrack( )	...\app.php:33
3	0.0033	430264	SpotifyWebAPI\SpotifyWebAPI->sendRequest( )	...\SpotifyWebAPI.php:1348

```

**Comment by jwilsson** [comment]
Hey!
It's a slight error in the documentation. The `SpotifyWebAPIException` class is missing its namespace.

Adding that will make it work:
```php
try {
    $track = $api->getTrack('non-existing-track');
} catch (SpotifyWebAPI\SpotifyWebAPIException $e) {
    echo 'Spotify API Error: ' . $e->getCode(); // Will be 404
}
```

**Comment by samcera** [comment]
Thanks! Working beautifully now 👍
