### ISSUE TITLE
get-playlist-images implementation 

### ISSUE THREAD

**Issue by djansen1987** [jwilsson/spotify-web-api-php#209]
Hi, Lets start of saying you helped me out creating an nice platform to play music quizzes (www.spotquiz.nl)

Het getting the quizzes i also fetch the spotify playlist image. I now do this through ` $api->getPlaylist($playlistid )` which works. But on a long list it takes a while and sometimes get hit with the API limit rate warning.

I also fetch way to much info at that time then i need. Looking at the Spotify Api i found that there was also a way to only fetch the playlist image. Don't see this being implemented at the moment, correct ? If so, is it a possibility to adapt it in to the module ?

[https://developer.spotify.com/console/get-playlist-images/](https://developer.spotify.com/console/get-playlist-images/)

**Comment by jwilsson** [comment]
Hey!
Cool! Really appreciate the link, always fun to see what people build with this library!

I didn't know about that method. Would you be interested in sending a PR for it? If not, no worries. I'll make sure it gets added.

**Comment by bmartus** [comment]
I am using this package, and will probably need to use this functionality.  

Had some free time real quick tonight, PR on its way in ..

**Comment by jwilsson** [comment]
I just tagged `4.1.0` containing this method.

@djansen1987 Thanks for bringing it to my attention!

@bmartus Thanks again for the PR!

**Comment by djansen1987** [comment]
Thanks guys!
