### ISSUE TITLE
Spotify introduced following and unfollowing of playlists

### ISSUE THREAD

**Issue by hvt** [jwilsson/spotify-web-api-php#21]
See https://developer.spotify.com/web-api/follow-playlist/ and https://developer.spotify.com/web-api/unfollow-playlist/.

When I've got some time I'll add support for it. If anyone's quicker than me, be my guest ;].

**Comment by vdesabou** [comment]
That's really good news, I've been waiting for that!
If I find time to work on adding it, I'll comment here, so that we don't duplicate our work!

**Comment by hvt** [comment]
:+1:

**Comment by jwilsson** [comment]
You guys :sparkles:

**Comment by vdesabou** [comment]
I was the quickest ! :smile:

**Comment by Pau1fitz** [comment]
Hi @vdesabou and @jwilsson. Apologies for the basic question. I am more of a javascript person and have used the spotify api with node before, however for this project I need to use php.

I am trying to follow a user playlist but for some reason it isn't working. If it is something really basic apologies in advance.

My code looks like this.

`step1.php`

```
<?php

require 'vendor/autoload.php';

$session = new SpotifyWebAPI\Session(
    '****',
    '*****',
    'http://***/step2.php'
);

$options = [
    'scope' => [
        'playlist-read-private',
        'user-read-private',
		'playlist-modify-public',
		'playlist-modify-private'
    ],
];

header('Location: ' . $session->getAuthorizeUrl($options));
die();

?>

```
My `step2.php` file looks like this

```
<?php

require 'vendor/autoload.php';

$session = new SpotifyWebAPI\Session('******', '*****', 'http://****/step2.php');
$api = new SpotifyWebAPI\SpotifyWebAPI();

// Request a access token using the code from Spotify
$session->requestAccessToken($_GET['code']);
$accessToken = $session->getAccessToken();

// Set the access token on the API wrapper
$api->setAccessToken($accessToken);

$me = $api->me();
$id = $me->id;

$api->followPlaylist($id, '2v3iNvBX8Ay1Gt2uXtUKUT');

echo 'success';
?>
```

**Comment by jwilsson** [comment]
@Pau1fitz Could you open a new issue, please? So we don't unnecessarily notify people. Thanks!

**Comment by Pau1fitz** [comment]
sure @jwilsson  will do that now. Thanks!
