### ISSUE TITLE
Having problems setting up spotify api with composer

### ISSUE THREAD

**Issue by ericlove02** [jwilsson/spotify-web-api-php#220]
I am trying to connect the Spotify Web api to my project, and I thought I had done so but am getting this error:
Fatal error: Uncaught Error: Class 'SpotifyWebAPI\SpotifyWebAPI' not found in D:\wamp64\www\app.php on line 4

Whenever I try to install the package with 'composer require jwilsson/spotify-web-api-php' I get this error:
The package name composer require jwilsson/spotify-web-api-php is invalid, it should be lowercase and have a vendor name, a forward slash, and a package name, matching: [a-z0-9_.-]+/[a-z0-9_.-]+

I'm trying to install it on a project on a WAMP server, so I'm not sure if that is what is causing my problem or not. This is my first time using composer, so I may be doing something wrong.

**Comment by jwilsson** [comment]
Hey!
That's a strange error from Composer. What is the exact command you're running?

**Comment by ericlove02** [comment]
I think I actually got it working. I think there was an issue with the compser.json file. I deleted it and ran composer require jwilsson/spotify-web-api-php and it seems to be working!
