### ISSUE TITLE
Docs suggestion

### ISSUE THREAD

**Issue by u20200522** [jwilsson/spotify-web-api-php#223]
Hi Jonathan,

I hope you're well.

This is a bit presumptuous, to suggest an improvement to your docs.

There is a lot of very useful information on the [methods reference docs](https://github.com/u20200522/spotify-web-api-php/blob/master/docs/method-reference/SpotifyWebAPI.md).

I have forked your repository and wondered if you thought adding a table of contents at the top of the page would be useful, [like this](https://github.com/u20200522/spotify-web-api-php/blob/master/docs/method-reference/SpotifyWebAPI.md)?

It might not be very sensible to have chopped it up like I have done - another option would be to have a simple list linking to every method since that keeps to the same alphabetical layout as the actual content.

It might be how my brain works but when scanning through the list of methods I find it useful to group them by the initial few characters of the method name (e.g. add, delete, follow, get etc), hence the nested lists layout.

I don't really know how GitHub works in terms of forks etc - but did the fork so I could edit the page on fork to show you what I mean.

Anyway, as I say, I don't want to be seen as saying I know better, it is just a suggestion.

Thanks

Jim

**Comment by u20200522** [comment]
Hi Jonathan,

That's interesting about the script - thanks for the info.

However, I'll now quietly exit and stop pretending I know stuff 😂😆🤣.

Thanks

Jim

**Comment by jwilsson** [comment]
Hi again Jim!
Just wanted to let you know I've updated the script and method reference with a table of contents.

Cheers,
Jonathan

**Comment by u20200522** [comment]
Hi Jonathan! That's great - thanks very much for that :-)
Wishing you a good weekend.
Thanks
Jim
