### ISSUE TITLE
how i can resume current track?

### ISSUE THREAD

**Issue by esurkov1** [jwilsson/spotify-web-api-php#225]
Hi! Sorry for my english...
i call play function without options and speakerId and i see

`<br />
<b>Fatal error</b>:  Uncaught SpotifyWebAPI\SpotifyWebAPIException: Malformed json in MYSERVER/vendor/jwilsson/spotify-web-api-php/src/Request.php:57
Stack trace:
#0 MYSERVER/vendor/jwilsson/spotify-web-api-php/src/Request.php(276): SpotifyWebAPI\Request-&gt;parseBody(Object(stdClass), 400)
#1 MYSERVERMYSERVER/vendor/jwilsson/spotify-web-api-php/src/Request.php(138): SpotifyWebAPI\Request-&gt;send('PUT', 'https://api.spo...', 'false', Array)
#2 MYSERVER/vendor/jwilsson/spotify-web-api-php/src/SpotifyWebAPI.php(115): SpotifyWebAPI\Request-&gt;api('PUT', '/v1/me/player/p...', 'false', Array)
#3 MYSERVER/spotify/vendor/jwilsson/spotify-web-api-php/src/SpotifyWebAPI.php(1660): SpotifyWebAPI\SpotifyWebAPI-&gt;sendRequest('PUT', '/v1/me/player/p...', 'false', Array)
#4 MYSERVER/alice.php(38): SpotifyWebAPI\SpotifyWebAPI-&gt; in <b>MYSERVER/vendor/jwilsson/spotify-web-api-php/src/Request.php</b> on line <b>57</b><br />`

how i can resume track after pause?

i use script:
`$api->play();
`

**Comment by jwilsson** [comment]
Hey!
Are you using the latest version (`4.2.2`)? This exact issue was fixed in that version.

Cheers!
