### ISSUE TITLE
followArtistsOrUsers not working?

### ISSUE THREAD

**Issue by u20200522** [jwilsson/spotify-web-api-php#229]
Hi Jonathan,

I hope you're well.

I noticed today that `followArtistsOrUsers` isn't working (no errors returned), and then when I went onto the Spotify website, and also the Spotify App, following artists doesn't end up with that artist appearing in My Library.

I wondered if it's working for you, via any of the above routes?

Thanks

Jim

**Comment by jwilsson** [comment]
Hey Jim!
On my end there seems to be a bit of a lag, the artist doesn't show up in the app immediately. It takes around 30 sec and I need to restart the Spotify app for it to show up.

I'd head over to their [developer forum](https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer) and see if anyone there can shed some light on it.

Cheers,
Jonathan

**Comment by u20200522** [comment]
Hi Jonathan - thanks for your reply.

The artists showed up today, so there was a delay, like you said.

Thanks

Jim
