### ISSUE TITLE
About play spotify track

### ISSUE THREAD

**Issue by abhiPHPDev** [jwilsson/spotify-web-api-php#230]
Hello sir,
I am new on programming.

I already fetched all track list according to your doument, but can't play the track/song. please suggest ho to play the song/track using your API.
Please responsd as soon as possible.
Thanks in advance
Abhishek

**Comment by jwilsson** [comment]
Hey!
It's not possible to play full length tracks using the Spotify Web API. There are 30 second samples available in the `preview_url` field returned from `SpotifyWebAPI::getTrack()` for example but nothing more than that. 

You could look into the [Web Playback SDK](https://developer.spotify.com/documentation/web-playback-sdk/) if you want to play tracks from Spotify.

**Comment by abhiPHPDev** [comment]
Thanks sir, thanks for your precious reply.
I already done it with Web playback SDK.
