### ISSUE TITLE
Question about method getTrack

### ISSUE THREAD

**Issue by yoqueseya** [jwilsson/spotify-web-api-php#231]
Hi, 
This is my first commment, I've just signed up. Im not sure if I should ask this here but:
Is there a method like getTrack('URI') but using NAME TRACK or ARTIST as parameters? URI is what I need to get in json.
I've just tried in Spotify Web Console API and it works but I don't know if I can with this repository.

Thanks!

**Comment by jwilsson** [comment]
Hey!
Did you find an answer since you closed the issue? If not, it sounds like the `SpotifyWebAPI::search()` method could be useful to you. Or if you point me to the endpoints you've used in the Spotify Web Console I could point you to the corresponding method in this library.

**Comment by yoqueseya** [comment]
Hi,
Yes! I found the search method minutes after writing it. Sorry for the inconvenience.
Thanks for answering.
