### ISSUE TITLE
 Fatal error

### ISSUE THREAD

**Issue by Fl3ecy** [jwilsson/spotify-web-api-php#235]
Hello,
im trying to use the spotify api, worked really good, but now i'm having some issues which i'm not being able to fix

/vendor/jwilsson/spotify-web-api-php/src/Request.php(239): SpotifyWebAPI\Request->handleResponseError(Object(stdClass), 403)
#1 /home/akaggdvp/public_html/test-flc/api/vendor/jwilsson/spotify-web-api-php/src/Request.php(129): SpotifyWebAPI\Request->send('GET', 'https://api.spo...', '', Array)
/vendor/jwilsson/spotify-web-api-php/src/SpotifyWebAPI.php(124): SpotifyWebAPI\Request->api('GET', '/v1/me', Array, Array)
/vendor/jwilsson/spotify-web-api-php/src/SpotifyWebAPI.php(1556): SpotifyWebAPI\SpotifyWebAPI->sendRequest('GET', '/v1/me')
vendor/index.php(16): SpotifyWebAPI\SpotifyWebAPI->me(Object(SpotifyWebAPI\Session))
#5 {main}
  thrown in /vendor/jwilsson/spotify-web-api-php/src/Request.php on line 59

removed the /home/ dir, etc.

I'm not sure if the "array" means that the client id and secret aren't getting read, but, if there's any possible fix, let me know.

**Comment by kasperkamperman** [comment]
I just ran in the same issue. You need to add the username of the account you want to give access to the API. This is a recent change and not documented in the readme. 
So next to edit settings, also set the users you'd like to give access.

**Comment by Fl3ecy** [comment]
> I just ran in the same issue. You need to add the username of the account you want to give access to the API. This is a recent change and not documented in the readme. So next to edit settings, also set the users you'd like to give access.

Alright, thanks. 

Also, is it possible to manage multiple users playlist via $api->addPlaylistTracks?

so for example, i have 2 access_tokens on my database, and i want to insert multiple tracks to both of those account at the same time, how is that possible?

**Comment by Fl3ecy** [comment]
I'm still getting the same error even after adding the account on dashboard at users and access

the 

SpotifyWebAPI\Request->send('GET', 'https://api.spo...', '', Array)
SpotifyWebAPI\Request->api('GET', '/v1/me', Array, Array)

no idea what this is, this works, then after a while just doesn't. Idk what this is...

**Comment by jwilsson** [comment]
Hey!
Could you wrap your call to `$api->me()` in a `try/catch` and print the exception so we get the exact error?

Regarding your other question, there shouldn't be any problems keeping multiple access tokens in a database and then changing the access tokens on a `SpotifyWebAPI` instance on the fly. Quick and dirty example:

```php
$accessTokens = [...]; // Fetched from your database

foreach ($accessTokens as $accessToken) {
  $api->setAccessToken($accessToken);

  $api->addPlaylistTracks(...);
}
```

And thanks @kasperkamperman, I'll add a note about it to the README.

**Comment by Fl3ecy** [comment]
Hello! I've tried using the Try { } then:

catch (Exception $e) {
        $ex = $e->getMessage();    
        die('Caught exception: '.$ex.'');
        }

the reponse i'm getting is "An unknown error occurred."

What do you think the error might be?

Thanks.

**Comment by jwilsson** [comment]
Hey!
Can you try again with this code, hopefully we'll get some more info:

```php
try {
  // Anything else you might have...

  $api->me();
} catch (Exception $e) {
   $lastResponse = $api->getRequest()->getLastResponse();

  var_dump($lastResponse);
}
```

**Comment by Fl3ecy** [comment]
There's a really long message from the last response:

`array(4) { ["body"]=> NULL ["headers"]=> array(14) { ["cache-control"]=> string(18) "private, max-age=0" ["access-control-allow-origin"]=> string(1) "*" ["access-control-allow-headers"]=> string(150) "Accept, App-Platform, Authorization, Content-Type, Origin, Retry-After, Spotify-App-Version, X-Cloud-Trace-Context, client-token, content-access-token" ["access-control-allow-methods"]=> string(38) "GET, POST, OPTIONS, PUT, DELETE, PATCH" ["access-control-allow-credentials"]=> string(4) "true" ["access-control-max-age"]=> string(6) "604800" ["content-encoding"]=> string(4) "gzip" ["content-length"]=> string(2) "71" ["strict-transport-security"]=> string(16) "max-age=31536000" ["x-content-type-options"]=> string(7) "nosniff" ["date"]=> string(29) "Sat, 02 Oct 2021 15:03:04 GMT" ["server"]=> string(5) "envoy" ["via"]=> string(28) "HTTP/2 edgeproxy, 1.1 google" ["alt-svc"]=> string(5) "clear" } ["status"]=> int(403) ["url"]=> string(29) "https://api.spotify.com/v1/me" }`

**Comment by jwilsson** [comment]
Hmm, I did some further digging with a new Spotify app and a user that wasn't added to that app and I got the exact same error. But once I added the user to the app it started working (it took a few minutes and might require a relog). 

So I just wanted as you to double check your app settings as mentioned above so see that the user is in fact added to the app.

If you're still getting errors could you add the following line to the `Request.php` file in the `vendor` directory in your project (should be located at `vendor/jwilsson/spotify-web-api-php/src/Request.php`) around line 223:

```php
[$headers, $body] = $this->splitResponse($response);
var_dump($body); // Add this line
$body = json_decode($body, $this->options['return_assoc']);
```

And see if we're getting an even better error. I'll also look into making this process easier with a proper way to do it without having to hack the library code yourself 😅

**Comment by Fl3ecy** [comment]
For sure. How exactly do you mean to add the user to the app manually? as i want the application to be fully automated. By user are your refering to the API account or the logining one from the site?

And i'll try to do that and give you a response soon.

**Comment by jwilsson** [comment]
Yeah, while your app is in Development Mode I'm afraid you'll need to add users to your app manually (by using the email they used to sign up for Spotify with), but when you're feeling ready to publish it you can request Extended Quota Mode from Spotify which will allow users to be added automatically. 

Spotify has some more info around it: https://developer.spotify.com/community/news/2021/05/27/improving-the-developer-and-user-experience-for-third-party-apps/

**Comment by jwilsson** [comment]
I've just pushed `5.0.1` which should give you a better exception message without having to hack the library files. Could you run it again wrapping the `$api->me()` call in a try/catch and printing the error? 

In my case Spotify replied with "User not registered in the Developer Dashboard" which went away as soon as I added the user to the app.

**Comment by Fl3ecy** [comment]
For sure, i'll try to do that just now. Should i call the catch exception 

```
$lastResponse = $api->getRequest()->getLastResponse();

  var_dump($lastResponse);
````

I'll give a response soon.

**Comment by Fl3ecy** [comment]
It says "User not registered in the Developer Dashboard". Now i understand the error. Thanks a LOT for hacking the files haha! So, i have 2 more questions. In order for the user to be automatically added i need to request the "extended quote" and how can i login more than 2 accounts on spotify? how can i unset the session in order to login multiple accounts at once on spotify from the same user?

**Comment by kasperkamperman** [comment]
Indeed in order to automatically add, you need extended quote (or probably apply to some rules) or add user e-mails manually. 
Why do you need to login in multiple accounts at the same time?
