### ISSUE TITLE
replacePlaylistTracks 

### ISSUE THREAD

**Issue by bmartus** [jwilsson/spotify-web-api-php#249]
It looks like the Spotify API limits this to 100 tracks. 

Is there a better way using this library to replace tracks on a larger playlist other than replacing with zero tracks and adding the new tracks in?

**Comment by jwilsson** [comment]
Hey!
I'm afraid the approach you're suggesting is the way to go. This is just a really thin wrapper around Spotify's APIs.

**Comment by bmartus** [comment]
Cool, just wanted to make sure I wasn't missing a better way.  Thanks!
