### ISSUE TITLE
Add "Check if Users Follow a Playlist" support

### ISSUE THREAD

**Issue by vdesabou** [jwilsson/spotify-web-api-php#25]
This was added last week: https://developer.spotify.com/web-api/check-user-following-playlist/

As usual, the first to work on the PR let the others know ;)

**Comment by jwilsson** [comment]
42939192801bf69f915093f5d997ceab7599f8f9 ;)

**Comment by vdesabou** [comment]
Oh sorry, I missed it :smile:
