### ISSUE TITLE
Old API URLs in source code

### ISSUE THREAD

**Issue by Xymph** [jwilsson/spotify-web-api-php#250]
In the SpotifyWebAPI.php and SpotifyWebAPIException.php source all URLs to [reference pages](https://developer.spotify.com/documentation/web-api/reference) follow an old pattern, and result in pages without the expected content. E.g. 
`https://developer.spotify.com/documentation/web-api/reference/#endpoint-search`
and
`@see https://developer.spotify.com/documentation/web-api/reference/object-model/#player-error-reasons`

Should be e.g. `https://developer.spotify.com/documentation/web-api/reference/#/operations/search`
Perhaps all can be updated?

**Comment by jwilsson** [comment]
Hey!
All links should be updated in the source code, I just haven't published a new release in a while. I'll get one published right away.

**Comment by Xymph** [comment]
Ah, apologies. I just installed the library via composer and forgot to check the main branch. Thanks for the superspeedy response.
