### ISSUE TITLE
createPlaylist() options documentation incomplete

### ISSUE THREAD

**Issue by Xymph** [jwilsson/spotify-web-api-php#251]
The options array for `createPlaylist()` [is shown](https://github.com/jwilsson/spotify-web-api-php/blob/main/docs/method-reference/SpotifyWebAPI.md#createplaylist) to support two, but it supports the `description` and `collaborative` options too (like with `updatePlaylist()`).

For [addPlaylistTracks()](https://github.com/jwilsson/spotify-web-api-php/blob/main/docs/method-reference/SpotifyWebAPI.md#addplaylisttracks), "appened" should be appended. (This one just jumped out, I didn't proofread the whole thing.)

**Comment by jwilsson** [comment]
Thanks for pointing it out!
