### ISSUE TITLE
Return All Genres?

### ISSUE THREAD

**Issue by infinitecheese** [jwilsson/spotify-web-api-php#254]
Hi Jonathan - I hope you're well.

I wondered if your Spotify Web API code has any provision to return all Genres?

I have used this:
$api->getGenreSeeds();

But the full list of Genres returned by e.g. https://discoverquickly.com/ (which I think also uses the Spotify API) is much larger - screenshot extract here:
https://snipboard.io/KekrMI.jpg

Full extract list also attached in text file.
[full-genre-list.txt](https://github.com/jwilsson/spotify-web-api-php/files/9638323/full-genre-list.txt)

Thanks!

Jim

**Comment by jwilsson** [comment]
Hey Jim!
I don't think there's an Spotify API endpoint to fetch the genres. But your question got me intrigued so I did some digging on https://discoverquickly.com/ and it looks like they're getting their data from https://everynoise.com/ (a request to https://discoverquickly.com/static/media/everynoise-genres.3d03bd3b.csv is made everytime you view the Genres page)

Hope this is of some help!

Cheers,
Jonathan

**Comment by infinitecheese** [comment]
Hi Jonathan - thanks for your quick reply!

That's very interesting about the CSV file that contains the list of genres.

Out of interest - how were you able to confirm that discoverquickly's "Genres" link extracts the data from that CSV file?

I tried a View Source, and an Inspect Element, and also checked on the browser Console for the XHR request when the Genres link is clicked but couldn't see the CSV bit.

Was curious what method(s) you used to find that?

Thanks again

Jim

**Comment by jwilsson** [comment]
I tried the same methods you did, without any luck. Then I saw the small "reload" icon on the genres page, clicking that I found a request for the CSV file in the browser's network tab 😄

**Comment by infinitecheese** [comment]
Thanks Jonathan - that's very useful to know!
Thanks again for your help
Jim
