### ISSUE TITLE
using the wrapper without composer

### ISSUE THREAD

**Issue by humpataa** [jwilsson/spotify-web-api-php#257]
I have downloaded and unzipped the code archive.
there is a folder src which has all the wrapper's class files (I guess).
how do I use it with plain simple PHP without composer.
please advise.
thank you.

**Comment by jwilsson** [comment]
Hey!
It's really not recommended to not use Composer or at least a PSR-4 compatible autoloader. But if you really want to, including all the files present in the `src` folder should do the trick:

```php
require_once 'src/SpotifyWebAPI.php';
require_once 'src/Session.php`;
And so on...
```

Hope this helps!
