### ISSUE TITLE
is jwilsson support spotify charts by country code ? 

### ISSUE THREAD

**Issue by mroscar20192020** [jwilsson/spotify-web-api-php#258]
i wanna get charts in US and FR can any one help me ?

**Comment by jwilsson** [comment]
Hey!
I'm not sure which charts you mean, is it one of [these](https://github.com/jwilsson/spotify-web-api-php/blob/c11395b37594c83dc9ea9802311ab1ece32a41ab/docs/examples/fetching-spotify-featured-content.md)? They all allow you to pass a specific country code.

**Comment by mroscar20192020** [comment]
> Hey! I'm not sure which charts you mean, is it one of [these](https://github.com/jwilsson/spotify-web-api-php/blob/c11395b37594c83dc9ea9802311ab1ece32a41ab/docs/examples/fetching-spotify-featured-content.md)? They all allow you to pass a specific country code.

I mean trends like country?=us u know what i mean is jwilsson support it ?

**Comment by jwilsson** [comment]
I'm sorry, I'm still not sure I follow. Every endpoint listed on https://developer.spotify.com/documentation/web-api/reference should be supported, if something's missing please let me know.
