### ISSUE TITLE
getting uncaught error

### ISSUE THREAD

**Issue by muhammadjan761** [jwilsson/spotify-web-api-php#260]
Fatal error: Uncaught SpotifyWebAPI\SpotifyWebAPIException: User not registered in the Developer Dashboard in /home/techtvto/public_html/clients/new/vendor/jwilsson/spotify-web-api-php/src/Request.php:59 Stack trace: #0 /home/techtvto/public_html/clients/new/vendor/jwilsson/spotify-web-api-php/src/Request.php(244): SpotifyWebAPI\Request->handleResponseError('User not regist...', 403) #1 /home/techtvto/public_html/clients/new/vendor/jwilsson/spotify-web-api-php/src/Request.php(132): SpotifyWebAPI\Request->send('GET', 'https://api.spo...', '', 'HTTP/2 403 \r\nca...') #2 /home/techtvto/public_html/clients/new/vendor/jwilsson/spotify-web-api-php/src/SpotifyWebAPI.php(118): SpotifyWebAPI\Request->api('GET', '/v1/me', Array, Array) #3 /home/techtvto/public_html/clients/new/vendor/jwilsson/spotify-web-api-php/src/SpotifyWebAPI.php(1673): SpotifyWebAPI\SpotifyWebAPI->sendRequest('GET', '/v1/me') #4 /home/techtvto/public_html/clients/new/spotify-login.php(17): SpotifyWebAPI\SpotifyWebAPI->me() #5 {main} thrown in /home/techtvto/public_html/clients/new/vendor/jwilsson/spotify-web-api-php/src/Request.php on line 59

**Comment by jwilsson** [comment]
Hey!
You need to add the user(s) you wish to use with your Spotify app to its allow list, check our [their docs](https://developer.spotify.com/documentation/web-api/guides/development-extended-quota-modes/) for more info.
