### ISSUE TITLE
Sometimes adding twice the track to the playlist

### ISSUE THREAD

**Issue by upgrader-dev** [jwilsson/spotify-web-api-php#263]
Hello,

I'm sometimes experiencing a double add of the track in the playlist.

My ´auto_retry' is set to off...

It looks like when the server response is getting late there is a second try and both lead to successfully adding the track to the playlist. 
I have no evidence about that, that's just my idea. 

Did anyone already encountered that behavior?

Thanks

Benjamin![image](https://github.com/jwilsson/spotify-web-api-php/assets/112260527/15ee8974-2efe-47f1-9b5e-621a4e9e9fe8)

**Comment by jwilsson** [comment]
Hey!
The `auto_retry` option only controls whether or not to retry requests when you hit the Spotify API rate limit. There's no other retry functionality in this library. 

I suspect it's something on Spotify's end that's the issue. I'd post an issue at their [Developer Forum](https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer) and see if anyone else has experienced the same issue.

**Comment by upgrader-dev** [comment]
Ok thank youEnvoyé de mon iPhoneLe 19 juin 2023 à 20:49, Jonathan Wilsson ***@***.***> a écrit :﻿
Hey!
The auto_retry option only controls whether or not to retry requests when you hit the Spotify API rate limit. There's no other retry functionality in this library.
I suspect it's something on Spotify's end that's the issue. I'd post an issue at their Developer Forum and see if anyone else has experienced the same issue.
