### ISSUE TITLE
Service not found exception when creating a playlist with $userId

### ISSUE THREAD

**Issue by WillyReyno** [jwilsson/spotify-web-api-php#266]
Hello,

I just upgraded to 5.7.0 but when `createPlaylist()` is provided with a `$userId`, the request ends up in `Service not found` exception because the endpoint doesn't seem to be correct.

According to [Create Playlist documentation](https://developer.spotify.com/documentation/web-api/reference/create-playlist) it should be `v1/users/{user_id}/playlists` and not `v1/{user_id}/playlists`.

Best regards!

**Comment by jwilsson** [comment]
Ah jeez, I guess I didn't test it enough. Sorry about that. 

I'll get a patch out ASAP.
