### ISSUE TITLE
How to set scopes when using Client Credentials method

### ISSUE THREAD

**Issue by beratgashii** [jwilsson/spotify-web-api-php#274]
Hi @jwilsson,

I am trying to create a simple script to return only $api->getMyCurrentTrack(); by using client credentials but without scopes it returns always HTTP ERROR 500 I checked the docs but i was unable to find a way to make this work?

Thanks,
B

**Comment by beratgashii** [comment]
I am trying to do everything on the same file and the same request, is this okay!

`require 'vendor/autoload.php';

use SpotifyWebAPI\Session;
use SpotifyWebAPI\SpotifyWebAPI;

// Function to request a new access token and fetch track data
function fetchTrackData() {
    $session = new Session(
    	'742d392cc1674afebbe0eb2719168cf4', // CLIENT_ID
    	'934c5d86c2a548378c25d49b82b66730', // CLIENT_SECRET
    );
    $session->requestCredentialsToken();
    $accessToken = $session->getAccessToken();

	$options = [
		'scope' => [
			'user-read-email',
			'user-read-currently-playing',
			'user-read-playback-state',
		],
	];

    // Create SpotifyWebAPI instance and set access token
    $api = new SpotifyWebAPI();
    $api->setAccessToken($accessToken);

    return $api->me();
}

// Fetch track data
echo '<pre>';
print_r(fetchTrackData());
echo '</pre>';`

**Comment by jwilsson** [comment]
Hey!
If you want to use scopes and access user information you need to use the [Authorization Code](https://github.com/jwilsson/spotify-web-api-php/blob/786666ffb00f3e1ba499771e28cba8b62974c7dd/docs/examples/access-token-with-authorization-code-flow.md) or [Proof Key for Code Exchange (PKCE)](https://github.com/jwilsson/spotify-web-api-php/blob/786666ffb00f3e1ba499771e28cba8b62974c7dd/docs/examples/access-token-with-pkce-flow.md) (PKCE is the recommended one for new applications) flows. The Client Credentials flow can only be used to fetch information about songs, artists, and so on.

Hope this clears things up!
