### ISSUE TITLE
replacePlaylistTracks tests for wrong response status

### ISSUE THREAD

**Issue by cdarken** [jwilsson/spotify-web-api-php#275]
Hi. I've been using your library, it works great!
But when updating a playlist I noticed the return false when actually I see the playlist updating.
The cause is the comparation with 201 of the response status in `replacePlaylistTracks` in `src/SpotifyWebAPI.php` when the Spotify api docs specify a 200 response in case of success (`https://developer.spotify.com/documentation/web-api/reference/reorder-or-replace-playlists-tracks`)

**Comment by jwilsson** [comment]
Hey!
It does indeed! Spotify must have changed that at some point 🤔 I'll get that sorted straight away.

**Comment by jwilsson** [comment]
`6.0.4` fixes it, thanks for the report!

**Comment by dragonattack** [comment]
Seems like that changed throughout other methods too, for example `addPlaylistTracks`
