### ISSUE TITLE
"Web API Exception: 400 - Missing required field: ids" when using addMyTracks()

### ISSUE THREAD

**Issue by vdesabou** [jwilsson/spotify-web-api-php#278]
It seems there was a change in https://developer.spotify.com/documentation/web-api/reference/save-tracks-user because I get `Web API Exception: 400 - Missing required field: ids` when using [addMyTracks](https://github.com/jwilsson/spotify-web-api-php/blob/482508df74e2b851be44d3c6ac7cbacae500ce7a/src/SpotifyWebAPI.php#L259)

Anyone seeing the same ?

**Comment by corpta** [comment]
I'm seeing the same thing happening.

**Comment by jwilsson** [comment]
This should be fixed in `6.1.1`.
