### ISSUE TITLE
Documentation Style

### ISSUE THREAD

**Issue by carlos-reynosa** [jwilsson/spotify-web-api-php#30]
Hello,

Just some feedback on the documentation. I'm currently looking at the [method reference documentation](http://jwilsson.github.io/spotify-web-api-php/method-reference/spotifywebapi.html) and i'm finding it a bit difficult to read. I think the documentation could be improved by adding indentation to anything under bolded text or a method name.

Hope that helps.

Regards,

Carlos

**Comment by jwilsson** [comment]
I'm not sure about adding indentation, however I've added borders between each method. 

Better?

**Comment by carlos-reynosa** [comment]
Hey, sorry for the late reply. Looks better. I guess you can close this now. Thanks for looking into it.

Regards,

Carlos
