### ISSUE TITLE
refreshAccessToken leads to blank page

### ISSUE THREAD

**Issue by AudricManaud** [jwilsson/spotify-web-api-php#34]
Hello,

I have a problem using the API: when I use the refreshAccessToken() function I get a blank page.
In local it works, but when I upload it on my server it stops working...Would you know why ?

Here's the code:

$session = new SpotifyWebAPI\Session('730c01f53af44936a0cc51459f0cb0ea', 'e1fc633ca35141bdb6edca04632850e7', '');
		$api = new SpotifyWebAPI\SpotifyWebAPI();
		$refreshToken = $_SESSION['refreshToken'];
		$session->setRefreshToken($refreshToken);
		$session->refreshAccessToken();
		$accessToken = $session->getAccessToken();
		// Request a access token using the code from Spotify
		$refreshToken = $session->getRefreshToken();
		$_SESSION['refreshToken'] = $refreshToken;
		// Set the new access token on the API wrapper
		$api->setAccessToken($accessToken);

**Comment by jwilsson** [comment]
Could you enable PHP error reporting, either via php.ini or by adding these lines at the top of the file:

```
error_reporting(-1);
ini_set('display_errors', 1);
```

And then post the error here?

**Comment by AudricManaud** [comment]
Hello :)
Thanks for helping, I tried this and it appears that the problem came from an Invalid URI...
I'm sorry to bother you for this kind of errors, but now I know how to display errors at least.

Thanks again,
Audric Manaud.
