### ISSUE TITLE
Fetching tracks from Top Charts

### ISSUE THREAD

**Issue by MaryCoding** [jwilsson/spotify-web-api-php#38]
Hi, I was wondering of a way to fetch top charts through the php wrapper. Here is a link that documents the charts endpoints http://charts.spotify.com/docs . Possible to incorporate that?

**Comment by jwilsson** [comment]
Hi,
Thanks for this. 

The scope of this project is the [Spotify Web API](https://developer.spotify.com/web-api/). However, there seems to be a [ticket open](https://github.com/spotify/web-api/issues/33) to implement these methods in the Web API. Once that's resolved I'd be more than happy to accept a PR for it/implement it here.
