### ISSUE TITLE
how to get full mp3 ?

### ISSUE THREAD

**Issue by navneetccna** [jwilsson/spotify-web-api-php#40]
i want to play full track is there any method to pull full track in place of only mp3 preview. what this link is dose actually ?
external_urls : https://open.spotify.com/track/5bVmuxniUeQh5dicBL6eQZ

i want to play song outside spotify is this possible ?

**Comment by skovmand** [comment]
Hi.

That is not possible, at least as mp3. Maybe some method exists to make an
embedded web player, I'm not sure.

**Comment by jwilsson** [comment]
Hi,
Sorry for the late reply.

As @skovmand has already pointed out, there isn't any possibility of this. There is [an issue](https://github.com/spotify/web-api/issues/57) about it on the official Spotify Web API repo though.

There is, however, a HTML widget which will allow you to embed a player: https://developer.spotify.com/technologies/widgets/spotify-play-button/
