### ISSUE TITLE
composer

### ISSUE THREAD

**Issue by onursevik** [jwilsson/spotify-web-api-php#47]
i cant use composer in my pc so that vendor/autoload.php is not works for me what is the alternative way to use sdk without that? Thanks

**Comment by jwilsson** [comment]
Well, the easiest way is to just include all the required files:
```php
require_once 'path/to/spotify-web-api-php/Request.php';
require_once 'path/to/spotify-web-api-php/Session.php';
require_once 'path/to/spotify-web-api-php/SpotifyWebAPI.php';
require_once 'path/to/spotify-web-api-php/SpotifyWebAPIException.php';
```

The second way involves creating your own autoloader, take a look at the docs for [spl_autoload_register()](http://php.net/manual/en/function.spl-autoload-register.php) on how to create something that suits your needs.
