### ISSUE TITLE
Access Token

### ISSUE THREAD

**Issue by onursevik** [jwilsson/spotify-web-api-php#48]
Hi again, im getting user's infos in normal way but when i change my page i can t reach api anymore. In error log it says Invalid authorization code when i set a session like ($_SESSION['spot_kod'] = $_GET['code'];) and trying to use it in another php file like;
$this->session->requestAccessToken($_SESSION['code']);
$this->api->setAccessToken($this->session->getAccessToken());

so what is problem here? how can i use api with a valid access token in another php file?

**Comment by jwilsson** [comment]
Hi!
The code is only valid once, to request an access token. You need to pass the access token along instead, for example:

First page
```php
$this->session->requestAccessToken($_GET['code']);
$_SESSION['spot_token'] = $this->session->getAccessToken();
```

Second page
```php
$this->api->setAccessToken($_SESSION['spot_token']);
```
