### ISSUE TITLE
Please allow Guzzle 6 as client

### ISSUE THREAD

**Issue by andig** [jwilsson/spotify-web-api-php#49]
...that would especially allow implementing retry handling to get over the rate limit like here: https://github.com/andig/dlf/blob/master/ClientFactory.php#L34

**Comment by jwilsson** [comment]
Hi!
We try to keep it simple and dependency free, just implementing the most basic HTTP class to support our needs. 

There's of course always possible for you to create your own simple wrapper around Guzzle and expose a compatible API to use with this library.

**Comment by andig** [comment]
> There's of course always possible for you to create your own simple wrapper around Guzzle and expose a compatible API to use with this library.

Done that. I have a guzzle adapter as well as a retry middleware that honors the api rate limit. Are you interested in a PR? If not I could roll my own repo. If yes- where would you like to put those? RequestAdapter\Guzzle namespace?

**Comment by jwilsson** [comment]
I think it's better suited in its own repo, but I'm glad to see some usage :)
