### ISSUE TITLE
Automatically support limit/next searches

### ISSUE THREAD

**Issue by andig** [jwilsson/spotify-web-api-php#50]
Current api implementation ignores limit/next return values. Large result sets should be automatically handled by the library.

**Comment by andig** [comment]
Actually, this may be more of a question: I have not found any way to even retrieve paged results without reimplementing the internal logic. Even calling e.g. `getUserPlaylist` with options for offset/limit it doesn't work as spotify wants to append a `/tracks` to the uri.

**Comment by jwilsson** [comment]
Hi,
We aim to keep this library as simple as possible and leaving these sort of things up to the user.

I'm not sure if `getUserPlaylist` was just an example or not, but there's also `getUserPlaylistTracks` which handles limit/offset. But if you happen to find a method that should support limit/offset but doesn't have it documented, PRs are always appreciated!

**Comment by andig** [comment]
I wasn't even aware of `getUserPlaylistTracks`, thank you!
