### ISSUE TITLE
Access token is always expired

### ISSUE THREAD

**Issue by tzfrs** [jwilsson/spotify-web-api-php#51]
Hey,

using your api to retrieve user's playlists and do some more stuff. When I call a method to the API I call my own method `refreshTokens`. This method checks if the token expiraton is less than 60 seconds and then updates the refresh tokens. However, I'm always running into the case true for `$this->session->getTokenExpiration() - time()` and I don't know why. It seems like the access token gets refreshed but as soon as I refresh my page it's empty again?

This is my constructor.

    public function __construct(
        Session $session,
        SpotifyWebAPI $spotifyWebAPI,
        Guard $guard,
        UserRepository $userRepository
    ) {
        $this->session = $session;
        $this->spotifyWebAPI = $spotifyWebAPI;
        $this->guard = $guard;

        if ($this->session->getAccessToken() !== '') {
            $this->spotifyWebAPI->setAccessToken($this->session->getAccessToken());
        }

        $this->userRepository = $userRepository;
    }

And this is the method I always call inside my methods calling the API.

    /**
     * Refreshes the token if the expiration is under the threshold or the force option is set to true.
     *
     * @param int  $threshold
     * @param bool $force
     */
    public function refreshTokens(int $threshold = 60, bool $force = false)
    {
        var_dump($this->session->getTokenExpiration()); // 0
        if ($this->session->getTokenExpiration() - time() < $threshold || $force) {
            $refreshToken = $this->getRefreshToken();
            var_dump($this->session->refreshAccessToken($refreshToken)); // true
            print $this->session->getTokenExpiration() - time(); // 3600
            $this->spotifyWebAPI->setAccessToken($this->session->getAccessToken());
            $this->updateTokensToUser();
        }
    }

What am I doing wrong here?

**Comment by jwilsson** [comment]
Hi,
Sorry for the late reply.

The library doesn't actually remember the time between page reloads, it just sets it whenever you request or refresh a token. If you save it yourself somewhere between page reloads and read the value from there it should work correctly.
