### ISSUE TITLE
How to catch a 429 and get the Retry-after?

### ISSUE THREAD

**Issue by Defcon0** [jwilsson/spotify-web-api-php#58]
Hello,

thanks for your great plugin. I'm currently testing it and one question comes to my mind:

As you of course know, there's a rate limit to spotify api. When it's reached, you get a http error code 429 and a Retry After header.

Is there any way to catch that information from your library? Is it saved to the "code" field in a SpotifyWebApiException and all I have to do is catch this Exception?

Bye Defcon0

**Comment by andig** [comment]
See https://github.com/andig/spotify-web-api-extensions for an extension that handles rate limiting.

**Comment by Defcon0** [comment]
Thanks for the advice

**Comment by jwilsson** [comment]
Hi @Defcon0,
An exception with a code of `429` will be thrown and @andig's extension contains some great pointers.

Cheers!
