### ISSUE TITLE
More graceful way to fail when encountering a non-existing track ID

### ISSUE THREAD

**Issue by justin-atp** [jwilsson/spotify-web-api-php#59]
When using the method $api->addUserPlaylistTracks() I've been encountering a fatal error whenever there is a non-existing track ID in the array of track IDs.  Unfortunately this comes up a lot due to certain tracks being disallowed in certain regions or tracks disappearing over time and it isn't possible to avoid this scenario altogether.

Would it be possible to have this result in a non-fatal warning rather than a fatal error?  Stack trace below:

```
Fatal error: Uncaught SpotifyWebAPI\SpotifyWebAPIException: Payload contains a non-existing ID in /src/Request.php:32
Stack trace:
#0 /src/Request.php(189): SpotifyWebAPI\Request->parseBody(Object(stdClass), 400)
#1 /src/Request.php(101): SpotifyWebAPI\Request->send('POST', 'https://api.spo...', '["spotify:track...', Array)
#2 /src/SpotifyWebAPI.php(132): SpotifyWebAPI\Request->api('POST', '/v1/users/someu...', '["spotify:track...', Array)
#3 /index.php(65): SpotifyWebAPI\SpotifyWebAPI->addUserPlaylistTracks('someuser', '6kZaxrc65H4F5T5...', '["spotify:track...')
#4 {main}
  thrown in /src/Request.php on line 32
```

**Comment by jwilsson** [comment]
Hmm, I think it's out of the scope for this library to handle these sort of things. It'll throw whenever the HTTP response code is outside `2xx` and then it's up to the user to handle it. 

If you `try/catch` the calls you can simply ignore the error if that's what you like.
