### ISSUE TITLE
new "recently played" endpoint

### ISSUE THREAD

**Issue by hycday** [jwilsson/spotify-web-api-php#66]
Hi,

Very nice API wrapper you developped here ! thank you !

Quick feature request here, Spotify just released the following endpoint, will you add it to your wrapper or no ? 

https://developer.spotify.com/web-api/web-api-personalization-endpoints/get-recently-played/

Thank you for your help and time !

**Comment by jwilsson** [comment]
@hycday You're not interested in submitting a PR for it?

If not, I'll try to add it ASAP if no one else beats me to it.

**Comment by hycday** [comment]
@jwilsson just did :)
