### ISSUE TITLE
callback part via cURL

### ISSUE THREAD

**Issue by hycday** [jwilsson/spotify-web-api-php#69]
Hi,

Is there anyway of handling the callback part via cURL and not with 
`header('Location: ' . $session->getAuthorizeUrl($scopes));`
This would allow the use of the script into mobile and other application that don't handle very well the redirection part...

Or is there a way to make a cURL call on a page.php that use this wrapper ? at the moment the cURL response is 302 as it redirects to the spotify authorize page...

Thanks !

**Comment by jwilsson** [comment]
Hmm, the callback part can be handled however you like. The user will, however, always be redirected back to the callback URL. But you can send the user to Spotify's authorization page anyway you like.

Some more info about the whole flow: https://developer.spotify.com/web-api/authorization-guide/#authorization-code-flow

**Comment by hycday** [comment]
so technically, there is no way to have :

http://mysite.com/index.php : with this wrapper coded, to fetch an artist page link, for example)

then 

http://hissite.com/curl.php : calling the above link in curl, to get the artist page link as a response

I guess it is not possible since at some point, there will be a redirection to Spotify auth page.
Unless it is possible to do so via cURL ?

**Comment by jwilsson** [comment]
If you don't need any user data, the [Client Credentials Flow](https://developer.spotify.com/web-api/authorization-guide/#client-credentials-flow) can be used without any redirects.

If you need user data, I don't think it's possible to do it just via cURL.
