### ISSUE TITLE
Method for audio analysis

### ISSUE THREAD

**Issue by craigharvi3** [jwilsson/spotify-web-api-php#70]
Would be great to have a method for audio analysis - https://developer.spotify.com/web-api/console/get-audio-analysis-track.

I've already implemented this in my local copy.

Let me know if it fits the scope. 

Cheers.

Craig

**Comment by jwilsson** [comment]
That's absolutely in the scope! I didn't know that method existed, a PR would be very much appreciated 😃

**Comment by craigharvi3** [comment]
Excellent, thanks!

What's the process for creating a PR. I can't seem to create a branch?

**Comment by andig** [comment]
First create a fork, then branch in your fork, then pr

**Comment by craigharvi3** [comment]
Cheers @andig 👍
