### ISSUE TITLE
Unsure on how to use the refresh token

### ISSUE THREAD

**Issue by Cannonb4ll** [jwilsson/spotify-web-api-php#72]
Currently creating an app where users basically login, and after they login they can hookup their spotify account to their account in the app im creating.

I get a accessToken and refreshToken, but what is the structural way to use this? I now have after a few minutes/hours that the accesstoken gets expired (which I save in my database).

How do I extend the accestoken with the refreshtoken, and when?

**Comment by jwilsson** [comment]
When the access token expires (either by you catching the error from Spotify or checking it against your database) you use the `Session::refreshAccessToken()` to request new tokens, which you then save in the database.

There's some more info and examples here: https://jwilsson.github.io/spotify-web-api-php/authorization.html#step-2

**Comment by Cannonb4ll** [comment]
Thank you. Would it be bad practise to execute that method each time the user logs in?

**Comment by jwilsson** [comment]
Hmm, I think the best way is to only request it when needed. I don't know if Spotify might start blocking your app or something if you request tokens too often.

**Comment by Cannonb4ll** [comment]
Alright, with a try-catch?

**Comment by jwilsson** [comment]
Yes, exactly! And when it fails, you refresh the token (if it's that kind of error).

**Comment by Cannonb4ll** [comment]
Alright I think I get that! So sorta like this:

```
            $api = new \SpotifyWebAPI\SpotifyWebAPI();

            try{
                $api->setAccessToken($token);

                $artists = object_get($api->getUserFollowedArtists(), 'artists.items');

            } catch (\Exception $e){
                $session = new \SpotifyWebAPI\Session('CLIENT_ID', 'CLIENT_SECRET', 'REDIRECT_URI');
                $session->refreshAccessToken($refreshToken);

                $accessToken = $session->getAccessToken();

                $api->setAccessToken($accessToken);

                $artists = object_get($api->getUserFollowedArtists(), 'artists.items');
            }

    // continue doing my things here
```

**Comment by jwilsson** [comment]
Yeah, I would check the code and message of the `Exception` too. Just to see if it's an expired access token error. I don't know the exakt message to look for though, but the status code should be `401`.

**Comment by Cannonb4ll** [comment]
Thank you for your help, I will do that. Solved! :)
