### ISSUE TITLE
"No token provided" error

### ISSUE THREAD

**Issue by hakhagmon** [jwilsson/spotify-web-api-php#85]
`PHP Fatal error:  Uncaught SpotifyWebAPI\SpotifyWebAPIException: No token provided in spoty\vendor\jwilsson\spotify-web-api-php\src\Request.php:39

Stack trace:
#0 spoty\vendor\jwilsson\spotify-web-api-php\src\Request.php(240): SpotifyWebAPI\Request->parseBody(Object(stdClass), 401)

#1 spoty\vendor\jwilsson\spotify-web-api-php\src\Request.php(108): SpotifyWebAPI\Request->send('GET', 'https://api.spo...', 'offset=0', Array)

#2 spoty\vendor\jwilsson\spotify-web-api-php\src\SpotifyWebAPI.php(561): SpotifyWebAPI\Request->api('GET', '/v1/artists/0rd...', Array, Array)

#3 spoty\spotycount.php(32): SpotifyWebAPI\SpotifyWebAPI->getArtistAlbums('0rdOduCP1sLQHOM...', Array)`

¯ \ _ (ツ) _ / ¯

**Comment by jwilsson** [comment]
This sounds it's related to Spotify's change on May 29th where they started requiring access tokens for all requests ([see this blog post](https://github.com/jwilsson/spotify-web-api-php/issues/85)).

I'm guessing you're not requesting any user information so the [Client Credentials Flow](https://github.com/jwilsson/spotify-web-api-php/blob/master/docs/examples/access-token-with-client-credentials-flow.md) should be enough for your use case.

**Comment by jwilsson** [comment]
Sorry, I messed up the link to the blog post. Here's the correct one: https://developer.spotify.com/news-stories/2017/01/27/removing-unauthenticated-calls-to-the-web-api/

**Comment by hakhagmon** [comment]
thx!
[Added this and everything turned out well](https://github.com/jwilsson/spotify-web-api-php/blob/master/docs/examples/access-token-with-client-credentials-flow.md)

**Comment by jwilsson** [comment]
Great, glad to hear it worked out!
