### ISSUE TITLE
Issue with basic example and displaying user details

### ISSUE THREAD

**Issue by Pau1fitz** [jwilsson/spotify-web-api-php#88]
I am working on the [basic examples in the docs which is strangely not showing the user's profile](https://github.com/jwilsson/spotify-web-api-php/blob/master/docs/examples/access-token-with-authorization-code-flow.md) on the front end.

I have taken a couple of approaches but cannot get it working. 

The code is the basic example and looks like this:

```
require 'vendor/autoload.php';

$session = new SpotifyWebAPI\Session(
    '****',
    '****',
    'test.html'
);

$api = new SpotifyWebAPI\SpotifyWebAPI();

if (isset($_GET['code'])) {
    $session->requestAccessToken($_GET['code']);
    $api->setAccessToken($session->getAccessToken());

    print_r($api->me());
} else {
    $options = [
        'scope' => [
            'user-read-email',
        ],
    ];

    header('Location: ' . $session->getAuthorizeUrl($options));
    die();
}
```

The url looks like `http://url/index.html?code=AQCH5_yl4bOPEvRaMfwQjpdm6esTfkUVwmZ5NEFlD0L9sfmst5-8FmwK0puU_9kI8yOK5i0uLUSYH00dW3kvl_gPCG0ARpgNaAdDoVTF33oOVY-qkh-EG3TRvmYj2u1c9qVAM8ea_g4JL7LOUPyQTdEPSFFwykpU_YCGzOo2grd0jR_Cu6L9DflC-xlappmP_yvFNLiXLzmS-qJIyla1g_NKfYZQJykGqKjozoBnJrBLDcllwNOwQ1pRRo2m`

I would have thought the php code would handle exchanging the code for a token but this doesn't appear to be happening.

**Comment by jwilsson** [comment]
Hi!
What's happening when you run the code? Do you get any error messages? Is the code interpreted as PHP (I'm asking since you're using `.html`-files)?

**Comment by Pau1fitz** [comment]
I have not got any error messages. I have also tried with a `php` file.
How shoulf the callback php file look like to show the user's profile if the html file may be the issue?

**Comment by jwilsson** [comment]
Hmm, are you using an absolute URL as the redirect uri? For example `http://localhost/test.php` in both the application you created at Spotify's developer site and in your code? Make sure they're an exact match, trailing slashes and everything. If they differ, that might be the issue.

I'm kinda at a loss here, I can't see anything wrong with your code. It should work.

**Comment by Pau1fitz** [comment]
it worked! typical! don't actually think there was any issue. just wasn't working for some reason :-) thanks for your help!

**Comment by jwilsson** [comment]
Great! Glad that we got it working!
