### ISSUE TITLE
Follow playlist example

### ISSUE THREAD

**Issue by Pau1fitz** [jwilsson/spotify-web-api-php#90]
Hi @vdesabou and @jwilsson. Apologies for the basic question. I am more of a javascript person and have used the spotify api with node before, however for this project I need to use php.

I am trying to follow a user playlist but for some reason it isn't working. If it is something really basic apologies in advance.

My code looks like this.

`step1.php`

```
<?php

require 'vendor/autoload.php';

$session = new SpotifyWebAPI\Session(
    '****',
    '*****',
    'http://***/step2.php'
);

$options = [
    'scope' => [
        'playlist-read-private',
        'user-read-private',
		'playlist-modify-public',
		'playlist-modify-private'
    ],
];

header('Location: ' . $session->getAuthorizeUrl($options));
die();

?>
```

My `step2.php` file looks like this

```
<?php

require 'vendor/autoload.php';

$session = new SpotifyWebAPI\Session('******', '*****', 'http://****/step2.php');
$api = new SpotifyWebAPI\SpotifyWebAPI();

// Request a access token using the code from Spotify
$session->requestAccessToken($_GET['code']);
$accessToken = $session->getAccessToken();

// Set the access token on the API wrapper
$api->setAccessToken($accessToken);

$me = $api->me();
$id = $me->id;

$api->followPlaylist($id, '2v3iNvBX8Ay1Gt2uXtUKUT');

echo 'success';
?>
```

**Comment by jwilsson** [comment]
Hi again!
When I'm running your code I'm getting a "Playlist doesn't exist" error back from the API. Whenever an error is returned from the API this library will throw. 

Try adding this to all your API calls so you'll be able to see any errors returned:
```php
try {
    $api->followPlaylist($id, '2v3iNvBX8Ay1Gt2uXtUKUT');
} catch (SpotifyWebAPI\SpotifyWebAPIException $e) {
    echo $e->getMessage();
    die();
}
``` 

Hope this helps!

**Comment by Pau1fitz** [comment]
@jwilsson the strange thing is I got that playlist id from their docs.[ If you go here](https://developer.spotify.com/web-api/console/put-playlist-followers/#complete) and 'fill sample data' it says playlist doesn't exist.

**Comment by jwilsson** [comment]
I'm taking that as it's working now? If not, just give me a shout!
