### ISSUE TITLE
Using this API without Composer

### ISSUE THREAD

**Issue by celsowhite** [jwilsson/spotify-web-api-php#92]
Hi, I'd love to use this API just by installing the src files within my Wordpress theme. Getting composer setup with WP is a bit of a headache and I'd rather just include the files manually. Do you have recommendations for doing so?

Right now I'm doing:

```
require_once('Request.php');
require_once('Session.php');
require_once('SpotifyWebAPI.php');
require_once('SpotifyWebAPIException.php');
```

**Comment by jwilsson** [comment]
Hi!
I'd recommend using a [autoloader](http://php.net/manual/en/function.spl-autoload-register.php) but making sure you only include the classes for `SpotifyWebAPI` with that (in case some plugin are using autoloaders too).

Quick, untested, example:
```php
spl_autoload_register(function ($class) {
    if (strpos($class, 'SpotifyWebAPI') !== false) {
        $path = path_join(get_stylesheet_directory(), '/classes/' . $class);

        require_once $path;
    }
});
```

You might run in to some trouble with other plugins registrering autoloaders too, though.

Your approach will work (I highly doubt we'll add any new files in the near future, causing something to break) but I highly recommend you to use an autoloader.

Hope this works!

**Comment by celsowhite** [comment]
Thanks @jwilsson! I'll give autoloader a try. My approach did end up working but I see the advantage of the autoloader.

Great wrapper. Thanks for the work.
