### ISSUE TITLE
Usage with Symfony framework

### ISSUE THREAD

**Issue by bun4uk** [jwilsson/spotify-web-api-php#93]
Have anybody used it with Symfony?

**Comment by jwilsson** [comment]
Hi!
The only thing I'm aware of is https://github.com/mmoreram/SpotifyApiBundle but that hasn't been updated in a few years.

I'll leave this issue open in case someone else knows of something.

**Comment by tchapi** [comment]
Just modify your **composer.json** to include the library in the classmap, so Composer adds it in the autoloader : 

```json
"autoload": {
        "psr-4": {
            "MainBundle\\": "src/MainBundle"
        },
        "classmap": [ 
            "app/AppKernel.php",
            "app/AppCache.php",
            "vendor/jwilsson/spotify-web-api-php/src" 
        ]
},
```

**Comment by tchapi** [comment]
I reckon this would be a nice addition in the docs for Symfony users
