### ISSUE TITLE
User playback functions

### ISSUE THREAD

**Issue by justin-vt** [jwilsson/spotify-web-api-php#94]
Should the user playback methods be working? Even when including all scopes I get a permissions error trying to do anything at all with devices. Spotify's own documentation seems to indicate this scope is only available to official SDKs:

"Control playback of a Spotify track. This scope is currently only available to Spotify native SDKs (for example, the iOS SDK and the Android SDK). The user must have a Spotify Premium account."

Maybe I'm missing something? 

Thanks!

**Comment by jwilsson** [comment]
Hi!
They should work (just tested it myself) but I think the account that you're trying to control the playback on needs to be a premium one. 

Those endpoints are marked as "Beta" by Spotify so there might be issues on their end as well.
