### ISSUE TITLE
getUserPlaylistTracks - only 100 Tracks

### ISSUE THREAD

**Issue by pscheich** [jwilsson/spotify-web-api-php#97]
Hey,
the function getUserPlaylistTracks returns only the first 100 Tracks from a playlist.
The default and max value for limit is 100.  
Do I have to check if there is more by myself to  get all tracks from a playlist?

> 

limit | Optional. The maximum number of tracks to return. Default: 100. Minimum: 1. Maximum: 100.
-- | --

Greetz 
ps

**Comment by jwilsson** [comment]
Hi!
Yeah, you can check the `next` field on each response. If it isn't `null` there are more results.

For example:
```php
$offset = 0;
$tracks = [];
$hasNext = true;

do {
    $response = $api->getUserPlaylistTracks('USER_ID', 'PLAYLIST_ID', [
        'offset' => $offset,
    ]);

    $offset += 100;
    $tracks = array_merge($tracks, $response->items);
    $hasNext = $response->next;
} while ($hasNext);

print_r($tracks);
```

Hope this helps!

**Comment by pscheich** [comment]
Hey,

thanks for this fast reply,  I will use your code.

Thank you.
